// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef _MINIS_CABINET_UI_H
#define _MINIS_CABINET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_overview.h"
#include "screens/ui_SHELVES_SCREEN.h"
#include "screens/ui_MINIATURES.h"
#include "screens/ui_SETTINGS.h"
#include "screens/ui_LIGHTS.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_cabinet_png);    // assets/img_cabinet.png
LV_IMG_DECLARE(
    ui_img_arrow_back_ios_new_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/arrow_back_ios_new_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_dashboard_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/dashboard_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_lightbulb_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/lightbulb_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_shelves_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/shelves_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_guardian_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/guardian_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_settings_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/settings_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_keyboard_double_arrow_left_32dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/keyboard_double_arrow_left_32dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_scene_24dp_b451ed_fill0_wght400_grad0_opsz24_png);    // assets/scene_24dp_B451ED_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_keyboard_double_arrow_right_32dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/keyboard_double_arrow_right_32dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_guardian_48dp_f04eb9_fill0_wght400_grad0_opsz48_png);    // assets/guardian_48dp_F04EB9_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_hexagon_40dp_ffffff_fill0_wght400_grad0_opsz40_png);    // assets/hexagon_40dp_FFFFFF_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_add_32dp_ffffff_fill0_wght400_grad0_opsz40_png);    // assets/add_32dp_FFFFFF_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_remove_32dp_ffffff_fill0_wght400_grad0_opsz40_png);    // assets/remove_32dp_FFFFFF_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_backlight_low_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/backlight_low_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_hexagon_72dp_00e4f6_fill0_wght400_grad0_opsz48_png);    // assets/hexagon_72dp_00E4F6_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_arrow_drop_down_72dp_00e4f6_fill0_wght400_grad0_opsz48_png);    // assets/arrow_drop_down_72dp_00E4F6_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_keyboard_double_arrow_left_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/keyboard_double_arrow_left_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(ui_img_mini_placeholder_png);    // assets/mini_placeholder.png
LV_IMG_DECLARE(
    ui_img_keyboard_double_arrow_right_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);    // assets/keyboard_double_arrow_right_40dp_00E4F6_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_check_40dp_75fbfd_fill0_wght400_grad0_opsz40_png);    // assets/check_40dp_75FBFD_FILL0_wght400_GRAD0_opsz40.png
LV_IMG_DECLARE(
    ui_img_close_40dp_ea33f7_fill0_wght400_grad0_opsz40_png);    // assets/close_40dp_EA33F7_FILL0_wght400_GRAD0_opsz40.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
