// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void autoMapLedsForLocation(lv_event_t * e);
void testLedsLocation(lv_event_t * e);
void saveLedsLocation(lv_event_t * e);
void scrollCardsToSelectedLocation(lv_event_t * e);
void updateMiniLocatinValue(lv_event_t * e);
void recordTestCallback(lv_event_t * e);
void setMinisLightColor(lv_event_t * e);
void setMinisLightsIntensity(lv_event_t * e);
void setCabinetLightColor(lv_event_t * e);
void setCabinetLightsIntensity(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
