// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "ui.h"

void scrollCardsToSelectedLocation(lv_event_t * e)
{
	// Your code here
}

void updateMiniLocatinValue(lv_event_t * e)
{
	// Your code here
}
