// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BORDER 0
#define UI_THEME_COLOR_CARD____________ 1
#define UI_THEME_COLOR_CYAN____________ 2
#define UI_THEME_COLOR_PINK____________ 3
#define UI_THEME_COLOR_PURPLE__________ 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Border[1];
extern const ui_theme_variable_t _ui_theme_alpha_Border[1];

extern const ui_theme_variable_t _ui_theme_color_Card____________[1];
extern const ui_theme_variable_t _ui_theme_alpha_Card____________[1];

extern const ui_theme_variable_t _ui_theme_color_Cyan____________[1];
extern const ui_theme_variable_t _ui_theme_alpha_Cyan____________[1];

extern const ui_theme_variable_t _ui_theme_color_Pink____________[1];
extern const ui_theme_variable_t _ui_theme_alpha_Pink____________[1];

extern const ui_theme_variable_t _ui_theme_color_Purple__________[1];
extern const ui_theme_variable_t _ui_theme_alpha_Purple__________[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
