// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Border[1] = {0x3B3E4D};
const ui_theme_variable_t _ui_theme_alpha_Border[1] = {255};

const ui_theme_variable_t _ui_theme_color_Card____________[1] = {0x101629};
const ui_theme_variable_t _ui_theme_alpha_Card____________[1] = {255};

const ui_theme_variable_t _ui_theme_color_Cyan____________[1] = {0x00E4F6};
const ui_theme_variable_t _ui_theme_alpha_Cyan____________[1] = {255};

const ui_theme_variable_t _ui_theme_color_Pink____________[1] = {0xF04EB9};
const ui_theme_variable_t _ui_theme_alpha_Pink____________[1] = {255};

const ui_theme_variable_t _ui_theme_color_Purple__________[1] = {0xB962EC};
const ui_theme_variable_t _ui_theme_alpha_Purple__________[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

