// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef _UI_COMP_LEFTBUTTON_H
#define _UI_COMP_LEFTBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT leftbutton
#define UI_COMP_LEFTBUTTON_LEFTBUTTON 0
#define _UI_COMP_LEFTBUTTON_NUM 1
lv_obj_t * ui_leftbutton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
