// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef _UI_COMP_HEADER2_H
#define _UI_COMP_HEADER2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT header2
#define UI_COMP_HEADER2_HEADER2 0
#define UI_COMP_HEADER2_CONTAINER2 1
#define UI_COMP_HEADER2_CONTAINER2_GO_BACK_BTN2 2
#define UI_COMP_HEADER2_CONTAINER2_HEADER_ICON2 3
#define UI_COMP_HEADER2_CONTAINER2_TITLE_SHELVES 4
#define UI_COMP_HEADER2_TIME4 5
#define _UI_COMP_HEADER2_NUM 6
lv_obj_t * ui_header2_create(lv_obj_t * comp_parent);
void ui_event_comp_header2_go_back_btn2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
