// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

void ui_event_comp_header2_go_back_btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_header2 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_overview, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_overview_screen_init);
    }
}

// COMPONENT header2

lv_obj_t * ui_header2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_header2;
    cui_header2 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_header2);
    lv_obj_set_width(cui_header2, 480);
    lv_obj_set_height(cui_header2, 45);
    lv_obj_set_align(cui_header2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_header2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_header2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_header2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(cui_header2, lv_color_hex(0x3B3E4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_header2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_header2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_header2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_header2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container2;
    cui_Container2 = lv_obj_create(cui_header2);
    lv_obj_remove_style_all(cui_Container2);
    lv_obj_set_width(cui_Container2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_go_back_btn2;
    cui_go_back_btn2 = lv_btn_create(cui_Container2);
    lv_obj_set_width(cui_go_back_btn2, 40);
    lv_obj_set_height(cui_go_back_btn2, 40);
    lv_obj_set_x(cui_go_back_btn2, 5);
    lv_obj_set_y(cui_go_back_btn2, 0);
    lv_obj_add_flag(cui_go_back_btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_go_back_btn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_go_back_btn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_go_back_btn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(cui_go_back_btn2, &ui_img_arrow_back_ios_new_40dp_00e4f6_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_header_icon2;
    cui_header_icon2 = lv_img_create(cui_Container2);
    lv_img_set_src(cui_header_icon2, &ui_img_shelves_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(cui_header_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_header_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(cui_header_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_header_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_header_icon2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_header_icon2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_header_icon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_header_icon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_TITLE_SHELVES;
    cui_TITLE_SHELVES = lv_label_create(cui_Container2);
    lv_obj_set_width(cui_TITLE_SHELVES, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_TITLE_SHELVES, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_TITLE_SHELVES, 50);
    lv_obj_set_y(cui_TITLE_SHELVES, 0);
    lv_obj_set_align(cui_TITLE_SHELVES, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_TITLE_SHELVES, "SHELVES");
    lv_obj_set_style_text_color(cui_TITLE_SHELVES, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_TITLE_SHELVES, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(cui_TITLE_SHELVES, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(cui_TITLE_SHELVES, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_TITLE_SHELVES, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_time4;
    cui_time4 = lv_label_create(cui_header2);
    lv_obj_set_width(cui_time4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_time4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_time4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_time4, "17:43");
    ui_object_set_themeable_style_property(cui_time4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(cui_time4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_font(cui_time4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER2_NUM);
    children[UI_COMP_HEADER2_HEADER2] = cui_header2;
    children[UI_COMP_HEADER2_CONTAINER2] = cui_Container2;
    children[UI_COMP_HEADER2_CONTAINER2_GO_BACK_BTN2] = cui_go_back_btn2;
    children[UI_COMP_HEADER2_CONTAINER2_HEADER_ICON2] = cui_header_icon2;
    children[UI_COMP_HEADER2_CONTAINER2_TITLE_SHELVES] = cui_TITLE_SHELVES;
    children[UI_COMP_HEADER2_TIME4] = cui_time4;
    lv_obj_add_event_cb(cui_header2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_header2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_go_back_btn2, ui_event_comp_header2_go_back_btn2, LV_EVENT_ALL, children);
    ui_comp_header2_create_hook(cui_header2);
    return cui_header2;
}

