// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

// COMPONENT BodyContainer

lv_obj_t * ui_BodyContainer_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BodyContainer;
    cui_BodyContainer = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_BodyContainer);
    lv_obj_set_width(cui_BodyContainer, 450);
    lv_obj_set_height(cui_BodyContainer, 245);
    lv_obj_set_x(cui_BodyContainer, 0);
    lv_obj_set_y(cui_BodyContainer, -15);
    lv_obj_set_align(cui_BodyContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(cui_BodyContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BODYCONTAINER_NUM);
    children[UI_COMP_BODYCONTAINER_BODYCONTAINER] = cui_BodyContainer;
    lv_obj_add_event_cb(cui_BodyContainer, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BodyContainer, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BodyContainer_create_hook(cui_BodyContainer);
    return cui_BodyContainer;
}

