// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

lv_obj_t * ui_LIGHTS = NULL;
lv_obj_t * ui_header4 = NULL;
lv_obj_t * ui_lightsScreen_body = NULL;
lv_obj_t * ui_minis_section = NULL;
lv_obj_t * ui_minisLights_colorwheel = NULL;
lv_obj_t * ui_minisWheel_text = NULL;
lv_obj_t * ui_minisIntentsity_slider = NULL;
lv_obj_t * ui_cabinet_section = NULL;
lv_obj_t * ui_cabinetLights_colorwheel = NULL;
lv_obj_t * ui_cabinetWheel_text = NULL;
lv_obj_t * ui_cabinetIntentsity_slider = NULL;
// event funtions
void ui_event_minisLights_colorwheel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setMinisLightColor(e);
    }
}

void ui_event_minisIntentsity_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setMinisLightsIntensity(e);
    }
}

void ui_event_cabinetLights_colorwheel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setCabinetLightColor(e);
    }
}

void ui_event_cabinetIntentsity_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setCabinetLightsIntensity(e);
    }
}

// build funtions

void ui_LIGHTS_screen_init(void)
{
    ui_LIGHTS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LIGHTS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LIGHTS, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LIGHTS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header4 = ui_header2_create(ui_LIGHTS);
    lv_obj_set_x(ui_header4, 0);
    lv_obj_set_y(ui_header4, 0);

    lv_img_set_src(ui_comp_get_child(ui_header4, UI_COMP_HEADER2_CONTAINER2_HEADER_ICON2),
                   &ui_img_lightbulb_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);

    lv_label_set_text(ui_comp_get_child(ui_header4, UI_COMP_HEADER2_CONTAINER2_TITLE_SHELVES), "LIGHTS");

    ui_lightsScreen_body = lv_obj_create(ui_LIGHTS);
    lv_obj_remove_style_all(ui_lightsScreen_body);
    lv_obj_set_width(ui_lightsScreen_body, lv_pct(95));
    lv_obj_set_height(ui_lightsScreen_body, lv_pct(80));
    lv_obj_set_x(ui_lightsScreen_body, 0);
    lv_obj_set_y(ui_lightsScreen_body, 22);
    lv_obj_set_align(ui_lightsScreen_body, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_lightsScreen_body, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_lightsScreen_body, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lightsScreen_body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightsScreen_body, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lightsScreen_body, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lightsScreen_body, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_lightsScreen_body, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minis_section = lv_obj_create(ui_lightsScreen_body);
    lv_obj_remove_style_all(ui_minis_section);
    lv_obj_set_width(ui_minis_section, lv_pct(48));
    lv_obj_set_height(ui_minis_section, lv_pct(100));
    lv_obj_set_x(ui_minis_section, -199);
    lv_obj_set_y(ui_minis_section, 25);
    lv_obj_set_align(ui_minis_section, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_minis_section, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_minisLights_colorwheel = lv_colorwheel_create(ui_minis_section, true);
    lv_obj_set_width(ui_minisLights_colorwheel, 150);
    lv_obj_set_height(ui_minisLights_colorwheel, 150);
    lv_obj_set_x(ui_minisLights_colorwheel, 0);
    lv_obj_set_y(ui_minisLights_colorwheel, 20);
    lv_obj_set_align(ui_minisLights_colorwheel, LV_ALIGN_TOP_MID);

    ui_minisWheel_text = lv_label_create(ui_minisLights_colorwheel);
    lv_obj_set_width(ui_minisWheel_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minisWheel_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minisWheel_text, 1);
    lv_obj_set_y(ui_minisWheel_text, -13);
    lv_obj_set_align(ui_minisWheel_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minisWheel_text, "MINIS");

    ui_minisIntentsity_slider = lv_slider_create(ui_minis_section);
    lv_slider_set_value(ui_minisIntentsity_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_minisIntentsity_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_minisIntentsity_slider, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_minisIntentsity_slider, 20);
    lv_obj_set_width(ui_minisIntentsity_slider, lv_pct(75));
    lv_obj_set_x(ui_minisIntentsity_slider, 0);
    lv_obj_set_y(ui_minisIntentsity_slider, -20);
    lv_obj_set_align(ui_minisIntentsity_slider, LV_ALIGN_BOTTOM_MID);

    ui_cabinet_section = lv_obj_create(ui_lightsScreen_body);
    lv_obj_remove_style_all(ui_cabinet_section);
    lv_obj_set_width(ui_cabinet_section, lv_pct(48));
    lv_obj_set_height(ui_cabinet_section, lv_pct(100));
    lv_obj_set_x(ui_cabinet_section, -199);
    lv_obj_set_y(ui_cabinet_section, 25);
    lv_obj_set_align(ui_cabinet_section, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cabinet_section, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cabinetLights_colorwheel = lv_colorwheel_create(ui_cabinet_section, true);
    lv_obj_set_width(ui_cabinetLights_colorwheel, 150);
    lv_obj_set_height(ui_cabinetLights_colorwheel, 150);
    lv_obj_set_x(ui_cabinetLights_colorwheel, 0);
    lv_obj_set_y(ui_cabinetLights_colorwheel, 20);
    lv_obj_set_align(ui_cabinetLights_colorwheel, LV_ALIGN_TOP_MID);

    ui_cabinetWheel_text = lv_label_create(ui_cabinetLights_colorwheel);
    lv_obj_set_width(ui_cabinetWheel_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cabinetWheel_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cabinetWheel_text, 1);
    lv_obj_set_y(ui_cabinetWheel_text, -13);
    lv_obj_set_align(ui_cabinetWheel_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cabinetWheel_text, "SHELVES");

    ui_cabinetIntentsity_slider = lv_slider_create(ui_cabinet_section);
    lv_slider_set_value(ui_cabinetIntentsity_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_cabinetIntentsity_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_cabinetIntentsity_slider, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_cabinetIntentsity_slider, 20);
    lv_obj_set_width(ui_cabinetIntentsity_slider, lv_pct(75));
    lv_obj_set_x(ui_cabinetIntentsity_slider, 0);
    lv_obj_set_y(ui_cabinetIntentsity_slider, -20);
    lv_obj_set_align(ui_cabinetIntentsity_slider, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_minisLights_colorwheel, ui_event_minisLights_colorwheel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minisIntentsity_slider, ui_event_minisIntentsity_slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cabinetLights_colorwheel, ui_event_cabinetLights_colorwheel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cabinetIntentsity_slider, ui_event_cabinetIntentsity_slider, LV_EVENT_ALL, NULL);

}

void ui_LIGHTS_screen_destroy(void)
{
    if(ui_LIGHTS) lv_obj_del(ui_LIGHTS);

    // NULL screen variables
    ui_LIGHTS = NULL;
    ui_header4 = NULL;
    ui_lightsScreen_body = NULL;
    ui_minis_section = NULL;
    ui_minisLights_colorwheel = NULL;
    ui_minisWheel_text = NULL;
    ui_minisIntentsity_slider = NULL;
    ui_cabinet_section = NULL;
    ui_cabinetLights_colorwheel = NULL;
    ui_cabinetWheel_text = NULL;
    ui_cabinetIntentsity_slider = NULL;

}
