// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_SHELVES_SCREEN_H
#define UI_SHELVES_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SHELVES_SCREEN
extern void ui_SHELVES_SCREEN_screen_init(void);
extern void ui_SHELVES_SCREEN_screen_destroy(void);
extern lv_obj_t * ui_SHELVES_SCREEN;
extern lv_obj_t * ui_header2;
extern lv_obj_t * ui_BodyContainerShelvesScreen;
extern lv_obj_t * ui_shelves_tabView;
extern lv_obj_t * ui_shelf_tabContent;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_uiShelfInputsContainer;
extern lv_obj_t * ui_uiShelfLocationsInputContainer;
extern lv_obj_t * ui_hex_icon;
extern lv_obj_t * ui_inputUpDowmLocation;
extern lv_obj_t * ui_addLocation_btn;
extern lv_obj_t * ui_locationInShef_label;
extern lv_obj_t * ui_substractLocation_btn;
extern lv_obj_t * ui_uiShelfLedsInputContainer;
extern lv_obj_t * ui_led_icon;
extern lv_obj_t * ui_inputUpDowmLocation1;
extern lv_obj_t * ui_addLeds_btn;
extern lv_obj_t * ui_ledsInShef_label;
extern lv_obj_t * ui_substractLeds_btn;
extern lv_obj_t * ui_shelfLocationSelector_container;
extern lv_obj_t * ui_locationInShelf_text;
extern lv_obj_t * ui_uiShelfPositionItem1;
extern lv_obj_t * ui_shelfLedMapping_container;
extern lv_obj_t * ui_uiLedItemContainer;
extern lv_obj_t * ui_ledItem;
extern lv_obj_t * ui_ledItemIndex_text;
extern lv_obj_t * ui_uiLedItemContainer1;
extern lv_obj_t * ui_uiLedItem1;
extern lv_obj_t * ui_uiLedItemLabel1;
extern lv_obj_t * ui_uiLedItemContainer2;
extern lv_obj_t * ui_uiLedItem2;
extern lv_obj_t * ui_uiLedItemLabel2;
extern lv_obj_t * ui_uiLedItemContainer4;
extern lv_obj_t * ui_uiLedItem4;
extern lv_obj_t * ui_uiLedItemLabel4;
extern lv_obj_t * ui_uiLedItemContainer5;
extern lv_obj_t * ui_uiLedItem5;
extern lv_obj_t * ui_uiLedItemLabel5;
extern lv_obj_t * ui_uiLedItemContainer3;
extern lv_obj_t * ui_uiLedItem3;
extern lv_obj_t * ui_uiLedItemLabel3;
extern lv_obj_t * ui_uiLedItemContainer12;
extern lv_obj_t * ui_uiLedItem12;
extern lv_obj_t * ui_uiLedItemLabel12;
extern lv_obj_t * ui_uiLedItemContainer8;
extern lv_obj_t * ui_uiLedItem8;
extern lv_obj_t * ui_uiLedItemLabel8;
extern lv_obj_t * ui_uiLedItemContainer9;
extern lv_obj_t * ui_uiLedItem9;
extern lv_obj_t * ui_uiLedItemLabel9;
extern lv_obj_t * ui_uiLedItemContainer10;
extern lv_obj_t * ui_uiLedItem10;
extern lv_obj_t * ui_uiLedItemLabel10;
extern lv_obj_t * ui_uiLedItemContainer11;
extern lv_obj_t * ui_uiLedItem11;
extern lv_obj_t * ui_uiLedItemLabel11;
extern lv_obj_t * ui_shelfActions_container;
extern lv_obj_t * ui_uiShelfLedMappingContainerOverly;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_startLabel;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_inputUpDowmLocation3;
extern lv_obj_t * ui_uiInputBtnUp3;
extern lv_obj_t * ui_uiInputUpDownTotalLedsValue;
extern lv_obj_t * ui_uiInputBtnDown3;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_startLabel1;
extern lv_obj_t * ui_SHELF_2;
extern lv_obj_t * ui_SHELF_3;
extern lv_obj_t * ui_SHELF_4;
extern lv_obj_t * ui_SHELF_5;
extern lv_obj_t * ui_ADD_SHELF;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

