// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef _MINIS_CABINET_UI_COMP_HOOK_H
#define _MINIS_CABINET_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_BodyContainer_create_hook(lv_obj_t * comp);
void ui_comp_header2_create_hook(lv_obj_t * comp);
void ui_comp_leftbutton_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
