// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

// COMPONENT leftbutton

lv_obj_t * ui_leftbutton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_leftbutton;
    cui_leftbutton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_leftbutton, 40);
    lv_obj_set_height(cui_leftbutton, 60);
    lv_obj_set_align(cui_leftbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_leftbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_leftbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_leftbutton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_leftbutton, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_leftbutton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(cui_leftbutton,
                                &ui_img_keyboard_double_arrow_left_40dp_00e4f6_fill0_wght400_grad0_opsz40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(cui_leftbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(cui_leftbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_leftbutton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(cui_leftbutton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(cui_leftbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_leftbutton, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_leftbutton, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_leftbutton, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_leftbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LEFTBUTTON_NUM);
    children[UI_COMP_LEFTBUTTON_LEFTBUTTON] = cui_leftbutton;
    lv_obj_add_event_cb(cui_leftbutton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_leftbutton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_leftbutton_create_hook(cui_leftbutton);
    return cui_leftbutton;
}

