// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_LIGHTS_SCREEN_H
#define UI_LIGHTS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_lights_screen
extern void ui_lights_screen_screen_init(void);
extern void ui_lights_screen_screen_destroy(void);
extern lv_obj_t * ui_lights_screen;
extern lv_obj_t * ui_header4;
extern lv_obj_t * ui_lightsScreen_body;
extern lv_obj_t * ui_minis_section;
extern void ui_event_minisLights_colorwheel(lv_event_t * e);
extern lv_obj_t * ui_minisLights_colorwheel;
extern lv_obj_t * ui_minisWheel_text;
extern lv_obj_t * ui_minisBrighness_valueLabel;
extern lv_obj_t * ui_cabinet_section;
extern void ui_event_cabinetBrightness_arc(lv_event_t * e);
extern lv_obj_t * ui_cabinetBrightness_arc;
extern lv_obj_t * ui_cabinetBrighness_valueLabel;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

