// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

lv_obj_t * ui_LIGHTS = NULL;
lv_obj_t * ui_header4 = NULL;
// event funtions

// build funtions

void ui_LIGHTS_screen_init(void)
{
    ui_LIGHTS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LIGHTS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LIGHTS, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LIGHTS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header4 = ui_header2_create(ui_LIGHTS);
    lv_obj_set_x(ui_header4, 0);
    lv_obj_set_y(ui_header4, 0);

    lv_img_set_src(ui_comp_get_child(ui_header4, UI_COMP_HEADER2_CONTAINER2_HEADER_ICON2),
                   &ui_img_lightbulb_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);

    lv_label_set_text(ui_comp_get_child(ui_header4, UI_COMP_HEADER2_CONTAINER2_TITLE_SHELVES), "LIGHTS");

}

void ui_LIGHTS_screen_destroy(void)
{
    if(ui_LIGHTS) lv_obj_del(ui_LIGHTS);

    // NULL screen variables
    ui_LIGHTS = NULL;
    ui_header4 = NULL;

}
