// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

lv_obj_t * ui_lights_screen = NULL;
lv_obj_t * ui_header4 = NULL;
lv_obj_t * ui_lightsScreen_body = NULL;
lv_obj_t * ui_minis_section = NULL;
lv_obj_t * ui_minisLights_colorwheel = NULL;
lv_obj_t * ui_minisWheel_text = NULL;
lv_obj_t * ui_minisBrighness_valueLabel = NULL;
lv_obj_t * ui_cabinet_section = NULL;
lv_obj_t * ui_cabinetBrightness_arc = NULL;
lv_obj_t * ui_cabinetBrighness_valueLabel = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_minisLights_colorwheel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onMinisLightColorChange(e);
    }
}

void ui_event_cabinetBrightness_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onCabinetBrightnessChange(e);
    }
}

// build funtions

void ui_lights_screen_screen_init(void)
{
    ui_lights_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_lights_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lights_screen, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lights_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header4 = ui_header2_create(ui_lights_screen);
    lv_obj_set_x(ui_header4, 0);
    lv_obj_set_y(ui_header4, 0);

    lv_img_set_src(ui_comp_get_child(ui_header4, UI_COMP_HEADER2_CONTAINER2_HEADER_ICON2),
                   &ui_img_lightbulb_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);

    lv_label_set_text(ui_comp_get_child(ui_header4, UI_COMP_HEADER2_CONTAINER2_TITLE_SHELVES), "LIGHTS");

    ui_lightsScreen_body = lv_obj_create(ui_lights_screen);
    lv_obj_remove_style_all(ui_lightsScreen_body);
    lv_obj_set_width(ui_lightsScreen_body, lv_pct(95));
    lv_obj_set_height(ui_lightsScreen_body, lv_pct(80));
    lv_obj_set_x(ui_lightsScreen_body, 0);
    lv_obj_set_y(ui_lightsScreen_body, 22);
    lv_obj_set_align(ui_lightsScreen_body, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_lightsScreen_body, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_lightsScreen_body, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lightsScreen_body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lightsScreen_body, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lightsScreen_body, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lightsScreen_body, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_lightsScreen_body, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minis_section = lv_obj_create(ui_lightsScreen_body);
    lv_obj_remove_style_all(ui_minis_section);
    lv_obj_set_width(ui_minis_section, lv_pct(48));
    lv_obj_set_height(ui_minis_section, lv_pct(100));
    lv_obj_set_x(ui_minis_section, -199);
    lv_obj_set_y(ui_minis_section, 25);
    lv_obj_set_align(ui_minis_section, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_minis_section, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_minisLights_colorwheel = lv_colorwheel_create(ui_minis_section, true);
    lv_obj_set_width(ui_minisLights_colorwheel, 200);
    lv_obj_set_height(ui_minisLights_colorwheel, 200);
    lv_obj_set_x(ui_minisLights_colorwheel, 2);
    lv_obj_set_y(ui_minisLights_colorwheel, 24);
    lv_obj_set_align(ui_minisLights_colorwheel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_minisLights_colorwheel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_minisWheel_text = lv_label_create(ui_minisLights_colorwheel);
    lv_obj_set_width(ui_minisWheel_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minisWheel_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minisWheel_text, -1);
    lv_obj_set_y(ui_minisWheel_text, -28);
    lv_obj_set_align(ui_minisWheel_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minisWheel_text, "MINIS");
    lv_obj_set_style_text_font(ui_minisWheel_text, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minisBrighness_valueLabel = lv_label_create(ui_minisLights_colorwheel);
    lv_obj_set_width(ui_minisBrighness_valueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minisBrighness_valueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minisBrighness_valueLabel, -1);
    lv_obj_set_y(ui_minisBrighness_valueLabel, 14);
    lv_obj_set_align(ui_minisBrighness_valueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minisBrighness_valueLabel, "54%");
    lv_obj_set_style_text_font(ui_minisBrighness_valueLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cabinet_section = lv_obj_create(ui_lightsScreen_body);
    lv_obj_remove_style_all(ui_cabinet_section);
    lv_obj_set_width(ui_cabinet_section, lv_pct(48));
    lv_obj_set_height(ui_cabinet_section, lv_pct(100));
    lv_obj_set_x(ui_cabinet_section, -199);
    lv_obj_set_y(ui_cabinet_section, 25);
    lv_obj_set_align(ui_cabinet_section, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cabinet_section, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cabinetBrightness_arc = lv_arc_create(ui_cabinet_section);
    lv_obj_set_width(ui_cabinetBrightness_arc, 200);
    lv_obj_set_height(ui_cabinetBrightness_arc, 200);
    lv_obj_set_x(ui_cabinetBrightness_arc, -9);
    lv_obj_set_y(ui_cabinetBrightness_arc, 1);
    lv_obj_set_align(ui_cabinetBrightness_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cabinetBrightness_arc,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_cabinetBrightness_arc, 76);

    ui_object_set_themeable_style_property(ui_cabinetBrightness_arc, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_cabinetBrightness_arc, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Pink____________);

    ui_cabinetBrighness_valueLabel = lv_label_create(ui_cabinetBrightness_arc);
    lv_obj_set_width(ui_cabinetBrighness_valueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cabinetBrighness_valueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cabinetBrighness_valueLabel, 5);
    lv_obj_set_y(ui_cabinetBrighness_valueLabel, 12);
    lv_obj_set_align(ui_cabinetBrighness_valueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cabinetBrighness_valueLabel, "76%");
    lv_obj_set_style_text_font(ui_cabinetBrighness_valueLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_cabinetBrightness_arc);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -2);
    lv_obj_set_y(ui_Label3, -30);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "CABINET");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_minisLights_colorwheel, ui_event_minisLights_colorwheel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cabinetBrightness_arc, ui_event_cabinetBrightness_arc, LV_EVENT_ALL, NULL);

}

void ui_lights_screen_screen_destroy(void)
{
    if(ui_lights_screen) lv_obj_del(ui_lights_screen);

    // NULL screen variables
    ui_lights_screen = NULL;
    ui_header4 = NULL;
    ui_lightsScreen_body = NULL;
    ui_minis_section = NULL;
    ui_minisLights_colorwheel = NULL;
    ui_minisWheel_text = NULL;
    ui_minisBrighness_valueLabel = NULL;
    ui_cabinet_section = NULL;
    ui_cabinetBrightness_arc = NULL;
    ui_cabinetBrighness_valueLabel = NULL;
    ui_Label3 = NULL;

}
