// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_LIGHTS_H
#define UI_LIGHTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LIGHTS
extern void ui_LIGHTS_screen_init(void);
extern void ui_LIGHTS_screen_destroy(void);
extern lv_obj_t * ui_LIGHTS;
extern lv_obj_t * ui_header4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

