// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_MINIATURES_H
#define UI_MINIATURES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MINIATURES
extern void ui_MINIATURES_screen_init(void);
extern void ui_MINIATURES_screen_destroy(void);
extern lv_obj_t * ui_MINIATURES;
extern lv_obj_t * ui_header1;
extern lv_obj_t * ui_BodyContainerMinis;
extern void ui_event_minis_cards_section(lv_event_t * e);
extern lv_obj_t * ui_minis_cards_section;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_leftbutton;
extern lv_obj_t * ui_SCROLL_MINIS_CONTAINER;
extern lv_obj_t * ui_card_info;
extern lv_obj_t * ui_mini_img;
extern lv_obj_t * ui_info;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_mini_info_Field;
extern lv_obj_t * ui_mini_info_label;
extern lv_obj_t * ui_mini_info_value;
extern lv_obj_t * ui_mini_info_Field1;
extern lv_obj_t * ui_mini_info_label1;
extern lv_obj_t * ui_mini_info_value1;
extern lv_obj_t * ui_mini_info_Field2;
extern lv_obj_t * ui_mini_info_label2;
extern lv_obj_t * ui_mini_info_value2;
extern lv_obj_t * ui_card_info1;
extern lv_obj_t * ui_mini_img1;
extern lv_obj_t * ui_info1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_mini_info_Field3;
extern lv_obj_t * ui_mini_info_label3;
extern lv_obj_t * ui_mini_info_value3;
extern lv_obj_t * ui_mini_info_Field4;
extern lv_obj_t * ui_mini_info_label4;
extern lv_obj_t * ui_mini_info_value4;
extern lv_obj_t * ui_mini_info_Field5;
extern lv_obj_t * ui_mini_info_label5;
extern lv_obj_t * ui_mini_info_value5;
extern lv_obj_t * ui_card_info2;
extern lv_obj_t * ui_mini_img2;
extern lv_obj_t * ui_info2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_mini_info_Field6;
extern lv_obj_t * ui_mini_info_label6;
extern lv_obj_t * ui_mini_info_value6;
extern lv_obj_t * ui_mini_info_Field7;
extern lv_obj_t * ui_mini_info_label7;
extern lv_obj_t * ui_mini_info_value7;
extern lv_obj_t * ui_mini_info_Field8;
extern lv_obj_t * ui_mini_info_label8;
extern lv_obj_t * ui_mini_info_value8;
extern lv_obj_t * ui_card_info3;
extern lv_obj_t * ui_mini_img3;
extern lv_obj_t * ui_info3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_mini_info_Field9;
extern lv_obj_t * ui_mini_info_label9;
extern lv_obj_t * ui_mini_info_value9;
extern lv_obj_t * ui_mini_info_Field10;
extern lv_obj_t * ui_mini_info_label10;
extern lv_obj_t * ui_mini_info_value10;
extern lv_obj_t * ui_mini_info_Field11;
extern lv_obj_t * ui_mini_info_label11;
extern lv_obj_t * ui_mini_info_value11;
extern lv_obj_t * ui_right_button;
extern lv_obj_t * ui_location_thumbnail1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_current_mini2;
extern lv_obj_t * ui_current_mini3;
extern lv_obj_t * ui_separator_location_mini;
extern lv_obj_t * ui_total_amoun_minis;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_uiModalOverlaySwapMiniLocation;
extern lv_obj_t * ui_Swap_mini_title;
extern lv_obj_t * ui_uiContainerSelectNewMiniLocation;
extern lv_obj_t * ui_uiLabelContainerNewMiniLocation;
extern lv_obj_t * ui_uiLabelNewMiniLocation;
extern lv_obj_t * ui_uiLabelNewMiniLocationValue;
extern lv_obj_t * ui_uiLabelNewMiniLocationSeparator;
extern lv_obj_t * ui_uiLabelNewMiniLocationTotalValue;
extern void ui_event_uiSliderSelectNewMiniLocation(lv_event_t * e);
extern lv_obj_t * ui_uiSliderSelectNewMiniLocation;
extern lv_obj_t * ui_uiActionsContainerSwapMini;
extern void ui_event_uiBtnActionSwapMini(lv_event_t * e);
extern lv_obj_t * ui_uiBtnActionSwapMini;
extern void ui_event_uiBtnActionCancelSwapMini(lv_event_t * e);
extern lv_obj_t * ui_uiBtnActionCancelSwapMini;
// CUSTOM VARIABLES
extern lv_obj_t * uic_header1_Container2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

