// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_MINIATURES_SCREEN_H
#define UI_MINIATURES_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_miniatures_screen
extern void ui_miniatures_screen_screen_init(void);
extern void ui_miniatures_screen_screen_destroy(void);
extern lv_obj_t * ui_miniatures_screen;
extern lv_obj_t * ui_header1;
extern lv_obj_t * ui_BodyContainerMinis;
extern void ui_event_minisCards_container(lv_event_t * e);
extern lv_obj_t * ui_minisCards_container;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_previousMini_btn;
extern lv_obj_t * ui_minisCard_scrollContainer;
extern lv_obj_t * ui_miniCardInfo_container;
extern lv_obj_t * ui_miniInfo_layout;
extern lv_obj_t * ui_miniInfoTitle_text;
extern lv_obj_t * ui_miniInfo_field;
extern lv_obj_t * ui_miniInfoFieldKey_text;
extern lv_obj_t * ui_miniInfoFieldValue_text;
extern lv_obj_t * ui_mini_info_Field1;
extern lv_obj_t * ui_mini_info_label1;
extern lv_obj_t * ui_mini_info_value1;
extern lv_obj_t * ui_mini_info_Field2;
extern lv_obj_t * ui_mini_info_label2;
extern lv_obj_t * ui_mini_info_value2;
extern lv_obj_t * ui_nextMini_btn;
extern lv_obj_t * ui_locationThumbnail_container;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_currentLocation_text;
extern lv_obj_t * ui_currentMini_label;
extern lv_obj_t * ui_separator_location_mini;
extern lv_obj_t * ui_totalMinis_label;
extern void ui_event_locationSelector_slider(lv_event_t * e);
extern lv_obj_t * ui_locationSelector_slider;
extern lv_obj_t * ui_uiModalOverlaySwapMiniLocation;
extern lv_obj_t * ui_Swap_mini_title;
extern lv_obj_t * ui_uiContainerSelectNewMiniLocation;
extern lv_obj_t * ui_uiLabelContainerNewMiniLocation;
extern lv_obj_t * ui_uiLabelNewMiniLocation;
extern lv_obj_t * ui_uiLabelNewMiniLocationValue;
extern lv_obj_t * ui_uiLabelNewMiniLocationSeparator;
extern lv_obj_t * ui_uiLabelNewMiniLocationTotalValue;
extern void ui_event_uiSliderSelectNewMiniLocation(lv_event_t * e);
extern lv_obj_t * ui_uiSliderSelectNewMiniLocation;
extern lv_obj_t * ui_uiActionsContainerSwapMini;
extern void ui_event_uiBtnActionSwapMini(lv_event_t * e);
extern lv_obj_t * ui_uiBtnActionSwapMini;
extern void ui_event_uiBtnActionCancelSwapMini(lv_event_t * e);
extern lv_obj_t * ui_uiBtnActionCancelSwapMini;
// CUSTOM VARIABLES
extern lv_obj_t * uic_header1_Container2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

