// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"
#include "../events/MiniaturesEvents.h"

lv_obj_t * uic_header1_Container2;
lv_obj_t * ui_miniatures_screen = NULL;
lv_obj_t * ui_header1 = NULL;
lv_obj_t * ui_BodyContainerMinis = NULL;
lv_obj_t * ui_minisCards_container = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_previousMini_btn = NULL;
lv_obj_t * ui_minisCard_scrollContainer = NULL;
lv_obj_t * ui_miniCardInfo_container = NULL;
lv_obj_t * ui_miniInfo_layout = NULL;
lv_obj_t * ui_miniInfoTitle_text = NULL;
lv_obj_t * ui_miniInfo_field = NULL;
lv_obj_t * ui_miniInfoFieldKey_text = NULL;
lv_obj_t * ui_miniInfoFieldValue_text = NULL;
lv_obj_t * ui_mini_info_Field1 = NULL;
lv_obj_t * ui_mini_info_label1 = NULL;
lv_obj_t * ui_mini_info_value1 = NULL;
lv_obj_t * ui_mini_info_Field2 = NULL;
lv_obj_t * ui_mini_info_label2 = NULL;
lv_obj_t * ui_mini_info_value2 = NULL;
lv_obj_t * ui_nextMini_btn = NULL;
lv_obj_t * ui_locationThumbnail_container = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_currentLocation_text = NULL;
lv_obj_t * ui_currentMini_label = NULL;
lv_obj_t * ui_separator_location_mini = NULL;
lv_obj_t * ui_totalMinis_label = NULL;
lv_obj_t * ui_locationSelector_slider = NULL;
lv_obj_t * ui_uiModalOverlaySwapMiniLocation = NULL;
lv_obj_t * ui_Swap_mini_title = NULL;
lv_obj_t * ui_uiContainerSelectNewMiniLocation = NULL;
lv_obj_t * ui_uiLabelContainerNewMiniLocation = NULL;
lv_obj_t * ui_uiLabelNewMiniLocation = NULL;
lv_obj_t * ui_uiLabelNewMiniLocationValue = NULL;
lv_obj_t * ui_uiLabelNewMiniLocationSeparator = NULL;
lv_obj_t * ui_uiLabelNewMiniLocationTotalValue = NULL;
lv_obj_t * ui_uiSliderSelectNewMiniLocation = NULL;
lv_obj_t * ui_uiActionsContainerSwapMini = NULL;
lv_obj_t * ui_uiBtnActionSwapMini = NULL;
lv_obj_t * ui_uiBtnActionCancelSwapMini = NULL;
// event funtions
void ui_event_minisCards_container(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_uiModalOverlaySwapMiniLocation, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_locationSelector_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_currentMini_label, target, "", "");
        minis_on_slider_changed(lv_slider_get_value(target));
    }
}

void ui_event_uiSliderSelectNewMiniLocation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_uiLabelNewMiniLocationValue, target, "", "");
    }
}

void ui_event_uiBtnActionSwapMini(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiModalOverlaySwapMiniLocation, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        updateMiniLocatinValue(e);
    }
}

void ui_event_uiBtnActionCancelSwapMini(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiModalOverlaySwapMiniLocation, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_miniatures_screen_screen_init(void)
{
    ui_miniatures_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_miniatures_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_miniatures_screen, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_miniatures_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header1 = ui_header2_create(ui_miniatures_screen);
    lv_obj_set_x(ui_header1, 0);
    lv_obj_set_y(ui_header1, 0);

    lv_img_set_src(ui_comp_get_child(ui_header1, UI_COMP_HEADER2_CONTAINER2_HEADER_ICON2),
                   &ui_img_guardian_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);

    lv_label_set_text(ui_comp_get_child(ui_header1, UI_COMP_HEADER2_CONTAINER2_TITLE_SHELVES), "MINIATURES");

    ui_BodyContainerMinis = lv_obj_create(ui_miniatures_screen);
    lv_obj_remove_style_all(ui_BodyContainerMinis);
    lv_obj_set_width(ui_BodyContainerMinis, 450);
    lv_obj_set_height(ui_BodyContainerMinis, 250);
    lv_obj_set_x(ui_BodyContainerMinis, 0);
    lv_obj_set_y(ui_BodyContainerMinis, -15);
    lv_obj_set_align(ui_BodyContainerMinis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_BodyContainerMinis, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BodyContainerMinis, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BodyContainerMinis, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_BodyContainerMinis, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BodyContainerMinis, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minisCards_container = lv_obj_create(ui_BodyContainerMinis);
    lv_obj_remove_style_all(ui_minisCards_container);
    lv_obj_set_width(ui_minisCards_container, lv_pct(100));
    lv_obj_set_height(ui_minisCards_container, lv_pct(75));
    lv_obj_set_align(ui_minisCards_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_minisCards_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_minisCards_container, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_minisCards_container,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_minisCards_container, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_minisCards_container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_minisCards_container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_minisCards_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_minisCards_container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_minisCards_container, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_minisCards_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_minisCards_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_minisCards_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_minisCards_container, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_minisCards_container);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(102));
    lv_obj_set_height(ui_Container9, lv_pct(96));
    lv_obj_set_align(ui_Container9, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_previousMini_btn = ui_leftbutton_create(ui_Container9);
    lv_obj_set_x(ui_previousMini_btn, 0);
    lv_obj_set_y(ui_previousMini_btn, 0);

    ui_minisCard_scrollContainer = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_minisCard_scrollContainer);
    lv_obj_set_width(ui_minisCard_scrollContainer, lv_pct(75));
    lv_obj_set_height(ui_minisCard_scrollContainer, lv_pct(100));
    lv_obj_set_align(ui_minisCard_scrollContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_minisCard_scrollContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_minisCard_scrollContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_minisCard_scrollContainer,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_minisCard_scrollContainer, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_minisCard_scrollContainer, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_minisCard_scrollContainer, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_pad_row(ui_minisCard_scrollContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_minisCard_scrollContainer, 52, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_minisCard_scrollContainer, LV_PART_SCROLLBAR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_minisCard_scrollContainer, LV_PART_SCROLLBAR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Cyan____________);

    ui_miniCardInfo_container = lv_obj_create(ui_minisCard_scrollContainer);
    lv_obj_remove_style_all(ui_miniCardInfo_container);
    lv_obj_set_width(ui_miniCardInfo_container, 325);
    lv_obj_set_height(ui_miniCardInfo_container, lv_pct(98));
    lv_obj_set_x(ui_miniCardInfo_container, 1);
    lv_obj_set_y(ui_miniCardInfo_container, 17);
    lv_obj_set_align(ui_miniCardInfo_container, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_miniCardInfo_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_miniCardInfo_container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_miniCardInfo_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_miniCardInfo_container, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_miniCardInfo_container, LV_SCROLL_SNAP_CENTER);

    ui_miniInfo_layout = lv_obj_create(ui_miniCardInfo_container);
    lv_obj_remove_style_all(ui_miniInfo_layout);
    lv_obj_set_width(ui_miniInfo_layout, lv_pct(100));
    lv_obj_set_height(ui_miniInfo_layout, lv_pct(100));
    lv_obj_set_align(ui_miniInfo_layout, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_miniInfo_layout, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_miniInfo_layout, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_miniInfo_layout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_miniInfoTitle_text = lv_label_create(ui_miniInfo_layout);
    lv_obj_set_width(ui_miniInfoTitle_text, lv_pct(100));
    lv_obj_set_height(ui_miniInfoTitle_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_miniInfoTitle_text, 18);
    lv_obj_set_y(ui_miniInfoTitle_text, -40);
    lv_obj_set_align(ui_miniInfoTitle_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_miniInfoTitle_text, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_miniInfoTitle_text, "Captain America");
    lv_obj_set_style_text_color(ui_miniInfoTitle_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_miniInfoTitle_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_miniInfoTitle_text, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_miniInfoTitle_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_miniInfoTitle_text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_miniInfoTitle_text, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_miniInfo_field = lv_obj_create(ui_miniInfo_layout);
    lv_obj_remove_style_all(ui_miniInfo_field);
    lv_obj_set_width(ui_miniInfo_field, lv_pct(100));
    lv_obj_set_height(ui_miniInfo_field, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_miniInfo_field, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_miniInfo_field, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_miniInfo_field, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_miniInfo_field, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_miniInfo_field, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_miniInfo_field, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_miniInfo_field, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_miniInfoFieldKey_text = lv_label_create(ui_miniInfo_field);
    lv_obj_set_width(ui_miniInfoFieldKey_text, lv_pct(40));
    lv_obj_set_height(ui_miniInfoFieldKey_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_miniInfoFieldKey_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_miniInfoFieldKey_text, "ARTIST");
    ui_object_set_themeable_style_property(ui_miniInfoFieldKey_text, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_miniInfoFieldKey_text, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_text_letter_space(ui_miniInfoFieldKey_text, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_miniInfoFieldKey_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_miniInfoFieldValue_text = lv_label_create(ui_miniInfo_field);
    lv_obj_set_width(ui_miniInfoFieldValue_text, lv_pct(60));
    lv_obj_set_height(ui_miniInfoFieldValue_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_miniInfoFieldValue_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_miniInfoFieldValue_text, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_miniInfoFieldValue_text, "STONE KING");

    ui_mini_info_Field1 = lv_obj_create(ui_miniInfo_layout);
    lv_obj_remove_style_all(ui_mini_info_Field1);
    lv_obj_set_width(ui_mini_info_Field1, lv_pct(100));
    lv_obj_set_height(ui_mini_info_Field1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mini_info_Field1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mini_info_Field1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_mini_info_Field1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_mini_info_Field1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_mini_info_Field1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_mini_info_Field1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mini_info_Field1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mini_info_label1 = lv_label_create(ui_mini_info_Field1);
    lv_obj_set_width(ui_mini_info_label1, lv_pct(40));
    lv_obj_set_height(ui_mini_info_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mini_info_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mini_info_label1, "DATE");
    ui_object_set_themeable_style_property(ui_mini_info_label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_mini_info_label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Pink____________);
    lv_obj_set_style_text_letter_space(ui_mini_info_label1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_mini_info_label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mini_info_value1 = lv_label_create(ui_mini_info_Field1);
    lv_obj_set_width(ui_mini_info_value1, lv_pct(60));
    lv_obj_set_height(ui_mini_info_value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mini_info_value1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_mini_info_value1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_mini_info_value1, "MAYO 2025");

    ui_mini_info_Field2 = lv_obj_create(ui_miniInfo_layout);
    lv_obj_remove_style_all(ui_mini_info_Field2);
    lv_obj_set_width(ui_mini_info_Field2, lv_pct(100));
    lv_obj_set_height(ui_mini_info_Field2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mini_info_Field2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mini_info_Field2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_mini_info_Field2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_mini_info_Field2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_mini_info_Field2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_mini_info_Field2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mini_info_Field2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mini_info_label2 = lv_label_create(ui_mini_info_Field2);
    lv_obj_set_width(ui_mini_info_label2, lv_pct(40));
    lv_obj_set_height(ui_mini_info_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mini_info_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mini_info_label2, "TAGS");
    ui_object_set_themeable_style_property(ui_mini_info_label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_mini_info_label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_letter_space(ui_mini_info_label2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_mini_info_label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mini_info_value2 = lv_label_create(ui_mini_info_Field2);
    lv_obj_set_width(ui_mini_info_value2, lv_pct(60));
    lv_obj_set_height(ui_mini_info_value2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mini_info_value2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_mini_info_value2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_mini_info_value2, "MARVEL, AVENGERS");
    lv_obj_clear_flag(ui_mini_info_value2, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_mini_info_value2, LV_SCROLL_SNAP_START);

    ui_nextMini_btn = lv_btn_create(ui_Container9);
    lv_obj_set_width(ui_nextMini_btn, 40);
    lv_obj_set_height(ui_nextMini_btn, 60);
    lv_obj_set_align(ui_nextMini_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextMini_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextMini_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_nextMini_btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nextMini_btn, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nextMini_btn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_nextMini_btn,
                                &ui_img_keyboard_double_arrow_right_40dp_00e4f6_fill0_wght400_grad0_opsz40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_nextMini_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_nextMini_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_nextMini_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_nextMini_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_nextMini_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_nextMini_btn, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_nextMini_btn, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_nextMini_btn, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_nextMini_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_locationThumbnail_container = lv_obj_create(ui_BodyContainerMinis);
    lv_obj_set_width(ui_locationThumbnail_container, lv_pct(100));
    lv_obj_set_height(ui_locationThumbnail_container, lv_pct(24));
    lv_obj_set_align(ui_locationThumbnail_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_locationThumbnail_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_locationThumbnail_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_locationThumbnail_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_locationThumbnail_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_locationThumbnail_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_locationThumbnail_container, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_locationThumbnail_container, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_locationThumbnail_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_locationThumbnail_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_locationThumbnail_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_locationThumbnail_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_locationThumbnail_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_locationThumbnail_container);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Container4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentLocation_text = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_currentLocation_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentLocation_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_currentLocation_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_currentLocation_text, "LOCATION");

    ui_currentMini_label = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_currentMini_label, 30);
    lv_obj_set_height(ui_currentMini_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_currentMini_label, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_currentMini_label, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_currentMini_label, "126");
    ui_object_set_themeable_style_property(ui_currentMini_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_currentMini_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_align(ui_currentMini_label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_separator_location_mini = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_separator_location_mini, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_separator_location_mini, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_separator_location_mini, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_separator_location_mini, "/");

    ui_totalMinis_label = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_totalMinis_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalMinis_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_totalMinis_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_totalMinis_label, "3");

    ui_locationSelector_slider = lv_slider_create(ui_locationThumbnail_container);
    lv_slider_set_range(ui_locationSelector_slider, 1, 126);
    lv_slider_set_value(ui_locationSelector_slider, 2, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_locationSelector_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_locationSelector_slider, 3, LV_ANIM_OFF);
    lv_obj_set_height(ui_locationSelector_slider, 10);
    lv_obj_set_width(ui_locationSelector_slider, lv_pct(92));
    lv_obj_set_align(ui_locationSelector_slider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_locationSelector_slider, lv_color_hex(0xB962EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_locationSelector_slider, 115, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_locationSelector_slider, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_locationSelector_slider, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Cyan____________);

    lv_obj_set_style_radius(ui_locationSelector_slider, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_locationSelector_slider, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_locationSelector_slider, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Cyan____________);
    ui_object_set_themeable_style_property(ui_locationSelector_slider, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_locationSelector_slider, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_locationSelector_slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_locationSelector_slider, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_locationSelector_slider, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_locationSelector_slider, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_locationSelector_slider, 8, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_uiModalOverlaySwapMiniLocation = lv_obj_create(ui_BodyContainerMinis);
    lv_obj_set_width(ui_uiModalOverlaySwapMiniLocation, lv_pct(80));
    lv_obj_set_height(ui_uiModalOverlaySwapMiniLocation, lv_pct(80));
    lv_obj_set_align(ui_uiModalOverlaySwapMiniLocation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiModalOverlaySwapMiniLocation, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiModalOverlaySwapMiniLocation, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiModalOverlaySwapMiniLocation, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_uiModalOverlaySwapMiniLocation,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_uiModalOverlaySwapMiniLocation, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiModalOverlaySwapMiniLocation, lv_color_hex(0x468CBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiModalOverlaySwapMiniLocation, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiModalOverlaySwapMiniLocation, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiModalOverlaySwapMiniLocation, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiModalOverlaySwapMiniLocation, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_uiModalOverlaySwapMiniLocation, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Card____________);
    lv_obj_set_style_text_font(ui_uiModalOverlaySwapMiniLocation, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiModalOverlaySwapMiniLocation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_uiModalOverlaySwapMiniLocation, 0, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_width(ui_uiModalOverlaySwapMiniLocation, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Swap_mini_title = lv_label_create(ui_uiModalOverlaySwapMiniLocation);
    lv_obj_set_width(ui_Swap_mini_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Swap_mini_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Swap_mini_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Swap_mini_title, "SWAP LOCATIONS");
    ui_object_set_themeable_style_property(ui_Swap_mini_title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_Swap_mini_title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Card____________);

    ui_uiContainerSelectNewMiniLocation = lv_obj_create(ui_uiModalOverlaySwapMiniLocation);
    lv_obj_set_width(ui_uiContainerSelectNewMiniLocation, lv_pct(100));
    lv_obj_set_height(ui_uiContainerSelectNewMiniLocation, lv_pct(47));
    lv_obj_set_align(ui_uiContainerSelectNewMiniLocation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiContainerSelectNewMiniLocation, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiContainerSelectNewMiniLocation, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiContainerSelectNewMiniLocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiContainerSelectNewMiniLocation, lv_color_hex(0x101629), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiContainerSelectNewMiniLocation, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiContainerSelectNewMiniLocation, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiContainerSelectNewMiniLocation, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiContainerSelectNewMiniLocation, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uiContainerSelectNewMiniLocation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiContainerSelectNewMiniLocation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiContainerSelectNewMiniLocation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiContainerSelectNewMiniLocation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelContainerNewMiniLocation = lv_obj_create(ui_uiContainerSelectNewMiniLocation);
    lv_obj_remove_style_all(ui_uiLabelContainerNewMiniLocation);
    lv_obj_set_width(ui_uiLabelContainerNewMiniLocation, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_uiLabelContainerNewMiniLocation, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_uiLabelContainerNewMiniLocation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLabelContainerNewMiniLocation, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiLabelContainerNewMiniLocation, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLabelContainerNewMiniLocation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_uiLabelContainerNewMiniLocation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uiLabelContainerNewMiniLocation, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_uiLabelContainerNewMiniLocation, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelContainerNewMiniLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelContainerNewMiniLocation, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelNewMiniLocation = lv_label_create(ui_uiLabelContainerNewMiniLocation);
    lv_obj_set_width(ui_uiLabelNewMiniLocation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelNewMiniLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelNewMiniLocation, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_uiLabelNewMiniLocation, "LOCATION");

    ui_uiLabelNewMiniLocationValue = lv_label_create(ui_uiLabelContainerNewMiniLocation);
    lv_obj_set_width(ui_uiLabelNewMiniLocationValue, 30);
    lv_obj_set_height(ui_uiLabelNewMiniLocationValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelNewMiniLocationValue, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_uiLabelNewMiniLocationValue, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_uiLabelNewMiniLocationValue, "126");
    ui_object_set_themeable_style_property(ui_uiLabelNewMiniLocationValue, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiLabelNewMiniLocationValue, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_align(ui_uiLabelNewMiniLocationValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelNewMiniLocationSeparator = lv_label_create(ui_uiLabelContainerNewMiniLocation);
    lv_obj_set_width(ui_uiLabelNewMiniLocationSeparator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelNewMiniLocationSeparator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelNewMiniLocationSeparator, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_uiLabelNewMiniLocationSeparator, "/");

    ui_uiLabelNewMiniLocationTotalValue = lv_label_create(ui_uiLabelContainerNewMiniLocation);
    lv_obj_set_width(ui_uiLabelNewMiniLocationTotalValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelNewMiniLocationTotalValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelNewMiniLocationTotalValue, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_uiLabelNewMiniLocationTotalValue, "3");

    ui_uiSliderSelectNewMiniLocation = lv_slider_create(ui_uiContainerSelectNewMiniLocation);
    lv_slider_set_range(ui_uiSliderSelectNewMiniLocation, 1, 126);
    lv_slider_set_value(ui_uiSliderSelectNewMiniLocation, 2, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_uiSliderSelectNewMiniLocation) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_uiSliderSelectNewMiniLocation, 3, LV_ANIM_OFF);
    lv_obj_set_height(ui_uiSliderSelectNewMiniLocation, 10);
    lv_obj_set_width(ui_uiSliderSelectNewMiniLocation, lv_pct(92));
    lv_obj_set_align(ui_uiSliderSelectNewMiniLocation, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_uiSliderSelectNewMiniLocation, lv_color_hex(0xB962EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiSliderSelectNewMiniLocation, 115, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_uiSliderSelectNewMiniLocation, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiSliderSelectNewMiniLocation, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Cyan____________);

    lv_obj_set_style_radius(ui_uiSliderSelectNewMiniLocation, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiSliderSelectNewMiniLocation, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiSliderSelectNewMiniLocation, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiSliderSelectNewMiniLocation, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_uiSliderSelectNewMiniLocation, LV_PART_KNOB | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_uiSliderSelectNewMiniLocation, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uiSliderSelectNewMiniLocation, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiSliderSelectNewMiniLocation, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiSliderSelectNewMiniLocation, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiSliderSelectNewMiniLocation, 8, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_uiActionsContainerSwapMini = lv_obj_create(ui_uiModalOverlaySwapMiniLocation);
    lv_obj_remove_style_all(ui_uiActionsContainerSwapMini);
    lv_obj_set_height(ui_uiActionsContainerSwapMini, 50);
    lv_obj_set_width(ui_uiActionsContainerSwapMini, lv_pct(100));
    lv_obj_set_align(ui_uiActionsContainerSwapMini, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiActionsContainerSwapMini, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiActionsContainerSwapMini, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiActionsContainerSwapMini, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiBtnActionSwapMini = lv_btn_create(ui_uiActionsContainerSwapMini);
    lv_obj_set_width(ui_uiBtnActionSwapMini, lv_pct(48));
    lv_obj_set_height(ui_uiBtnActionSwapMini, lv_pct(100));
    lv_obj_set_align(ui_uiBtnActionSwapMini, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiBtnActionSwapMini, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiBtnActionSwapMini, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiBtnActionSwapMini, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnActionSwapMini, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBtnActionSwapMini, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_uiBtnActionSwapMini, &ui_img_check_40dp_75fbfd_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiBtnActionSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiBtnActionSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiBtnActionSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiBtnActionSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_uiBtnActionSwapMini, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uiBtnActionSwapMini, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiBtnActionSwapMini, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiBtnActionSwapMini, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiBtnActionSwapMini, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiBtnActionCancelSwapMini = lv_btn_create(ui_uiActionsContainerSwapMini);
    lv_obj_set_width(ui_uiBtnActionCancelSwapMini, lv_pct(48));
    lv_obj_set_height(ui_uiBtnActionCancelSwapMini, lv_pct(100));
    lv_obj_set_align(ui_uiBtnActionCancelSwapMini, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiBtnActionCancelSwapMini, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiBtnActionCancelSwapMini, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiBtnActionCancelSwapMini, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiBtnActionCancelSwapMini, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBtnActionCancelSwapMini, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_uiBtnActionCancelSwapMini, &ui_img_close_40dp_ea33f7_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiBtnActionCancelSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_uiBtnActionCancelSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Pink____________);
    ui_object_set_themeable_style_property(ui_uiBtnActionCancelSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_uiBtnActionCancelSwapMini, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Pink____________);
    lv_obj_set_style_border_width(ui_uiBtnActionCancelSwapMini, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uiBtnActionCancelSwapMini, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiBtnActionCancelSwapMini, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiBtnActionCancelSwapMini, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiBtnActionCancelSwapMini, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_minisCards_container, ui_event_minisCards_container, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_locationSelector_slider, ui_event_locationSelector_slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiSliderSelectNewMiniLocation, ui_event_uiSliderSelectNewMiniLocation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBtnActionSwapMini, ui_event_uiBtnActionSwapMini, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiBtnActionCancelSwapMini, ui_event_uiBtnActionCancelSwapMini, LV_EVENT_ALL, NULL);

    /* App-layer events */
    lv_obj_add_event_cb(ui_miniatures_screen, ui_event_miniatures_screen_loaded, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(ui_previousMini_btn, ui_event_previousMini_btn, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_nextMini_btn, ui_event_nextMini_btn, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_minisCards_container, ui_event_minis_locate, LV_EVENT_CLICKED, NULL);
    uic_header1_Container2 = ui_comp_get_child(ui_header1, UI_COMP_HEADER2_CONTAINER2);

}

void ui_miniatures_screen_screen_destroy(void)
{
    if(ui_miniatures_screen) lv_obj_del(ui_miniatures_screen);

    // NULL screen variables
    ui_miniatures_screen = NULL;
    ui_header1 = NULL;
    uic_header1_Container2 = NULL;
    ui_BodyContainerMinis = NULL;
    ui_minisCards_container = NULL;
    ui_Container9 = NULL;
    ui_previousMini_btn = NULL;
    ui_minisCard_scrollContainer = NULL;
    ui_miniCardInfo_container = NULL;
    ui_miniInfo_layout = NULL;
    ui_miniInfoTitle_text = NULL;
    ui_miniInfo_field = NULL;
    ui_miniInfoFieldKey_text = NULL;
    ui_miniInfoFieldValue_text = NULL;
    ui_mini_info_Field1 = NULL;
    ui_mini_info_label1 = NULL;
    ui_mini_info_value1 = NULL;
    ui_mini_info_Field2 = NULL;
    ui_mini_info_label2 = NULL;
    ui_mini_info_value2 = NULL;
    ui_nextMini_btn = NULL;
    ui_locationThumbnail_container = NULL;
    ui_Container4 = NULL;
    ui_currentLocation_text = NULL;
    ui_currentMini_label = NULL;
    ui_separator_location_mini = NULL;
    ui_totalMinis_label = NULL;
    ui_locationSelector_slider = NULL;
    ui_uiModalOverlaySwapMiniLocation = NULL;
    ui_Swap_mini_title = NULL;
    ui_uiContainerSelectNewMiniLocation = NULL;
    ui_uiLabelContainerNewMiniLocation = NULL;
    ui_uiLabelNewMiniLocation = NULL;
    ui_uiLabelNewMiniLocationValue = NULL;
    ui_uiLabelNewMiniLocationSeparator = NULL;
    ui_uiLabelNewMiniLocationTotalValue = NULL;
    ui_uiSliderSelectNewMiniLocation = NULL;
    ui_uiActionsContainerSwapMini = NULL;
    ui_uiBtnActionSwapMini = NULL;
    ui_uiBtnActionCancelSwapMini = NULL;

}
