// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_OVERVIEW_H
#define UI_OVERVIEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_overview
extern void ui_overview_screen_init(void);
extern void ui_overview_screen_destroy(void);
extern lv_obj_t * ui_overview;
extern lv_obj_t * ui_decorative_bg;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_go_back_btn;
extern lv_obj_t * ui_header_icon;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_TITLE;
extern lv_obj_t * ui_navbar;
extern void ui_event_screen_lights_btn(lv_event_t * e);
extern lv_obj_t * ui_screen_lights_btn;
extern lv_obj_t * ui_Image7;
extern void ui_event_screen_shelves_btn(lv_event_t * e);
extern lv_obj_t * ui_screen_shelves_btn;
extern lv_obj_t * ui_Image2;
extern void ui_event_screen_minis_btn(lv_event_t * e);
extern lv_obj_t * ui_screen_minis_btn;
extern lv_obj_t * ui_minis_icon_40;
extern void ui_event_screen_settings_btn(lv_event_t * e);
extern lv_obj_t * ui_screen_settings_btn;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_actions;
extern lv_obj_t * ui_scenes_section;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_lights_toggle;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_minis_overview;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

