// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

lv_obj_t * ui_overview_screen = NULL;
lv_obj_t * ui_overviewBg_img = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_go_back_btn = NULL;
lv_obj_t * ui_header_icon = NULL;
lv_obj_t * ui_time_label = NULL;
lv_obj_t * ui_wifi_label = NULL;
lv_obj_t * ui_mqtt_label = NULL;
lv_obj_t * ui_overviewTitle_text = NULL;
lv_obj_t * ui_navbar = NULL;
lv_obj_t * ui_screenLights_btn = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_screenShelves_btn = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_screenMinis_btn = NULL;
lv_obj_t * ui_minis_icon_40 = NULL;
lv_obj_t * ui_screen_settings_btn = NULL;
lv_obj_t * ui_screenSettings_btn = NULL;
lv_obj_t * ui_actions = NULL;
lv_obj_t * ui_scenes_section = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_previousScene_btn = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_currentScene_icon = NULL;
lv_obj_t * ui_currentScene_label = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_nextScene_btn = NULL;
lv_obj_t * ui_lights_toggle = NULL;
lv_obj_t * ui_lights_switch = NULL;
lv_obj_t * ui_lightsSwitch_text = NULL;
lv_obj_t * ui_minis_overview = NULL;
lv_obj_t * ui_minis_icon = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_minisAmount_label = NULL;
lv_obj_t * ui_minisAmount_text = NULL;
// event funtions
void ui_event_screenLights_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_lights_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_lights_screen_screen_init);
    }
}

void ui_event_screenShelves_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
    }
}

void ui_event_screenMinis_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_miniatures_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_miniatures_screen_screen_init);
    }
}

void ui_event_screen_settings_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_settings_screen_screen_init);
    }
}

// build funtions

void ui_overview_screen_screen_init(void)
{
    ui_overview_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_overview_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_overview_screen, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_overview_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overviewBg_img = lv_img_create(ui_overview_screen);
    lv_img_set_src(ui_overviewBg_img, &ui_img_img_cabinet_png);
    lv_obj_set_width(ui_overviewBg_img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_overviewBg_img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_overviewBg_img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_overviewBg_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_overviewBg_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header = lv_obj_create(ui_overview_screen);
    lv_obj_remove_style_all(ui_header);
    lv_obj_set_width(ui_header, 480);
    lv_obj_set_height(ui_header, 45);
    lv_obj_set_align(ui_header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_header, lv_color_hex(0x3B3E4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_go_back_btn = lv_btn_create(ui_header);
    lv_obj_set_width(ui_go_back_btn, 40);
    lv_obj_set_height(ui_go_back_btn, 40);
    lv_obj_set_x(ui_go_back_btn, 5);
    lv_obj_set_y(ui_go_back_btn, 0);
    lv_obj_add_flag(ui_go_back_btn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_go_back_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_go_back_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_go_back_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_go_back_btn, &ui_img_arrow_back_ios_new_40dp_00e4f6_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_icon = lv_img_create(ui_header);
    lv_img_set_src(ui_header_icon, &ui_img_dashboard_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_header_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_header_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_header_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_header_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time_label = lv_label_create(ui_header);
    lv_obj_set_width(ui_time_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_label, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_time_label, "17:43");
    ui_object_set_themeable_style_property(ui_time_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_time_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_font(ui_time_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_label = lv_label_create(ui_header);
    lv_obj_set_width(ui_wifi_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_wifi_label, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_wifi_label, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_wifi_label, -90);
    lv_obj_set_y(ui_wifi_label, 0);
    lv_label_set_text(ui_wifi_label, "WIFI");
    lv_obj_set_style_text_font(ui_wifi_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_wifi_label, lv_color_hex(0x555577), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifi_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mqtt_label = lv_label_create(ui_header);
    lv_obj_set_width(ui_mqtt_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_mqtt_label, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_mqtt_label, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_mqtt_label, -150);
    lv_obj_set_y(ui_mqtt_label, 0);
    lv_label_set_text(ui_mqtt_label, "MQTT");
    lv_obj_set_style_text_font(ui_mqtt_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_mqtt_label, lv_color_hex(0x555577), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mqtt_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overviewTitle_text = lv_label_create(ui_header);
    lv_obj_set_width(ui_overviewTitle_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_overviewTitle_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_overviewTitle_text, 50);
    lv_obj_set_y(ui_overviewTitle_text, 0);
    lv_obj_set_align(ui_overviewTitle_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_overviewTitle_text, "OVERVIEW");
    lv_obj_set_style_text_color(ui_overviewTitle_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_overviewTitle_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_overviewTitle_text, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_overviewTitle_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_overviewTitle_text, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navbar = lv_obj_create(ui_overview_screen);
    lv_obj_remove_style_all(ui_navbar);
    lv_obj_set_width(ui_navbar, 480);
    lv_obj_set_height(ui_navbar, 56);
    lv_obj_set_align(ui_navbar, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_navbar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_navbar, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_navbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_navbar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_navbar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_navbar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_navbar, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_navbar, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_navbar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_navbar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenLights_btn = lv_btn_create(ui_navbar);
    lv_obj_set_width(ui_screenLights_btn, 100);
    lv_obj_set_height(ui_screenLights_btn, 48);
    lv_obj_set_align(ui_screenLights_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screenLights_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_screenLights_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screenLights_btn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screenLights_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_screenLights_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(ui_screenLights_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_screenLights_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_screenLights_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_screenLights_btn);
    lv_img_set_src(ui_Image7, &ui_img_lightbulb_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_screenShelves_btn = lv_btn_create(ui_navbar);
    lv_obj_set_width(ui_screenShelves_btn, 100);
    lv_obj_set_height(ui_screenShelves_btn, 48);
    lv_obj_set_align(ui_screenShelves_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_screenShelves_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_screenShelves_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screenShelves_btn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screenShelves_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_screenShelves_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(ui_screenShelves_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_screenShelves_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_screenShelves_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_screenShelves_btn);
    lv_img_set_src(ui_Image2, &ui_img_shelves_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_screenMinis_btn = lv_btn_create(ui_navbar);
    lv_obj_set_width(ui_screenMinis_btn, 100);
    lv_obj_set_height(ui_screenMinis_btn, 48);
    lv_obj_set_align(ui_screenMinis_btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_screenMinis_btn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_screenMinis_btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_screenMinis_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_screenMinis_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screenMinis_btn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screenMinis_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_screenMinis_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(ui_screenMinis_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_screenMinis_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_screenMinis_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screenMinis_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_screenMinis_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_font(ui_screenMinis_btn, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minis_icon_40 = lv_img_create(ui_screenMinis_btn);
    lv_img_set_src(ui_minis_icon_40, &ui_img_guardian_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_minis_icon_40, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_minis_icon_40, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_minis_icon_40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minis_icon_40, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_minis_icon_40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_screen_settings_btn = lv_btn_create(ui_navbar);
    lv_obj_set_width(ui_screen_settings_btn, 100);
    lv_obj_set_height(ui_screen_settings_btn, 48);
    lv_obj_set_align(ui_screen_settings_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screen_settings_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_screen_settings_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screen_settings_btn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screen_settings_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_screen_settings_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(ui_screen_settings_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_screen_settings_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_screen_settings_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screenSettings_btn = lv_img_create(ui_screen_settings_btn);
    lv_img_set_src(ui_screenSettings_btn, &ui_img_settings_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_screenSettings_btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_screenSettings_btn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_screenSettings_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screenSettings_btn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_screenSettings_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_actions = lv_obj_create(ui_overview_screen);
    lv_obj_remove_style_all(ui_actions);
    lv_obj_set_width(ui_actions, 224);
    lv_obj_set_height(ui_actions, 200);
    lv_obj_set_x(ui_actions, -15);
    lv_obj_set_y(ui_actions, -5);
    lv_obj_set_align(ui_actions, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_actions, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_actions, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_actions, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_actions, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_actions, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_actions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_actions, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_actions, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_actions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scenes_section = lv_obj_create(ui_actions);
    lv_obj_remove_style_all(ui_scenes_section);
    lv_obj_set_width(ui_scenes_section, 220);
    lv_obj_set_height(ui_scenes_section, 60);
    lv_obj_set_align(ui_scenes_section, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_scenes_section, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_scenes_section, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scenes_section, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_scenes_section, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_scenes_section, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_scenes_section, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_scenes_section, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_scenes_section, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_scenes_section, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_text_font(ui_scenes_section, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_scenes_section);
    lv_obj_set_width(ui_Button3, 40);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_previousScene_btn = lv_img_create(ui_Button3);
    lv_img_set_src(ui_previousScene_btn, &ui_img_keyboard_double_arrow_left_32dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_previousScene_btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_previousScene_btn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_previousScene_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_previousScene_btn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_previousScene_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_scenes_section);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_text_font(ui_Container1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentScene_icon = lv_img_create(ui_Container1);
    lv_img_set_src(ui_currentScene_icon, &ui_img_scene_24dp_b451ed_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_currentScene_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentScene_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_currentScene_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_currentScene_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_currentScene_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_currentScene_label = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_currentScene_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentScene_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentScene_label, 20);
    lv_obj_set_y(ui_currentScene_label, 0);
    lv_obj_set_align(ui_currentScene_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentScene_label, "RANDOM");
    lv_obj_clear_flag(ui_currentScene_label,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_currentScene_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_currentScene_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_currentScene_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_currentScene_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_scenes_section);
    lv_obj_set_width(ui_Button1, 40);
    lv_obj_set_height(ui_Button1, 40);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextScene_btn = lv_img_create(ui_Button1);
    lv_img_set_src(ui_nextScene_btn, &ui_img_keyboard_double_arrow_right_32dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_nextScene_btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nextScene_btn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_nextScene_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextScene_btn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_nextScene_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lights_toggle = lv_obj_create(ui_actions);
    lv_obj_remove_style_all(ui_lights_toggle);
    lv_obj_set_width(ui_lights_toggle, 220);
    lv_obj_set_height(ui_lights_toggle, 60);
    lv_obj_set_align(ui_lights_toggle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_lights_toggle, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_lights_toggle, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_add_flag(ui_lights_toggle, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_lights_toggle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_lights_toggle, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_lights_toggle, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lights_toggle, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lights_toggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lights_toggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lights_toggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_lights_toggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_lights_toggle, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_font(ui_lights_toggle, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_x(ui_lights_toggle, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_y(ui_lights_toggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_toggle, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_shadow_width(ui_lights_toggle, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_lights_toggle, 2, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(ui_lights_toggle, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(ui_lights_toggle, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lights_switch = lv_switch_create(ui_lights_toggle);
    lv_obj_set_width(ui_lights_switch, 50);
    lv_obj_set_height(ui_lights_switch, 30);
    lv_obj_set_align(ui_lights_switch, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Cyan____________);

    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_lights_switch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lights_switch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_lights_switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_lights_switch, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_shadow_width(ui_lights_switch, 10, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_lights_switch, 1, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_lights_switch, lv_color_hex(0x00E4F6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lights_switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lights_switch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lights_switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_lightsSwitch_text = lv_label_create(ui_lights_toggle);
    lv_obj_set_width(ui_lightsSwitch_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightsSwitch_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lightsSwitch_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightsSwitch_text, "LIGHTS");

    ui_minis_overview = lv_obj_create(ui_actions);
    lv_obj_remove_style_all(ui_minis_overview);
    lv_obj_set_width(ui_minis_overview, 220);
    lv_obj_set_height(ui_minis_overview, 60);
    lv_obj_set_align(ui_minis_overview, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_minis_overview, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_minis_overview, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_minis_overview, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_minis_overview, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_minis_overview, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_minis_overview, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Pink____________);
    lv_obj_set_style_border_width(ui_minis_overview, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_minis_overview, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_minis_overview, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_minis_overview, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_minis_overview, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_minis_overview, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_minis_overview, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_minis_overview, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_minis_overview, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Pink____________);
    lv_obj_set_style_text_font(ui_minis_overview, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minis_icon = lv_img_create(ui_minis_overview);
    lv_img_set_src(ui_minis_icon, &ui_img_guardian_48dp_f04eb9_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_minis_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minis_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_minis_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minis_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_minis_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_minis_overview);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 50);
    lv_obj_set_width(ui_Container7, lv_pct(65));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_minisAmount_label = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_minisAmount_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minisAmount_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_minisAmount_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minisAmount_label, "146");
    lv_label_set_recolor(ui_minisAmount_label, "true");
    lv_obj_set_style_text_color(ui_minisAmount_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minisAmount_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minisAmount_label, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minisAmount_text = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_minisAmount_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minisAmount_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_minisAmount_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minisAmount_text, "MINIATURES");

    lv_obj_add_event_cb(ui_screenLights_btn, ui_event_screenLights_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenShelves_btn, ui_event_screenShelves_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenMinis_btn, ui_event_screenMinis_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen_settings_btn, ui_event_screen_settings_btn, LV_EVENT_ALL, NULL);

    /* Scene navigation */
    lv_obj_add_event_cb(ui_Button3, ui_event_previousScene_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_nextScene_btn, LV_EVENT_ALL, NULL);

    /* Cabinet lights toggle */
    lv_obj_add_event_cb(ui_lights_switch, ui_event_lights_switch, LV_EVENT_ALL, NULL);

    /* Refresh view when screen becomes active */
    lv_obj_add_event_cb(ui_overview_screen, ui_event_overview_screen_loaded, LV_EVENT_SCREEN_LOADED, NULL);

}

void ui_overview_screen_screen_destroy(void)
{
    if(ui_overview_screen) lv_obj_del(ui_overview_screen);

    // NULL screen variables
    ui_overview_screen = NULL;
    ui_overviewBg_img = NULL;
    ui_header = NULL;
    ui_go_back_btn = NULL;
    ui_header_icon = NULL;
    ui_time_label = NULL;
    ui_wifi_label = NULL;
    ui_mqtt_label = NULL;
    ui_overviewTitle_text = NULL;
    ui_navbar = NULL;
    ui_screenLights_btn = NULL;
    ui_Image7 = NULL;
    ui_screenShelves_btn = NULL;
    ui_Image2 = NULL;
    ui_screenMinis_btn = NULL;
    ui_minis_icon_40 = NULL;
    ui_screen_settings_btn = NULL;
    ui_screenSettings_btn = NULL;
    ui_actions = NULL;
    ui_scenes_section = NULL;
    ui_Button3 = NULL;
    ui_previousScene_btn = NULL;
    ui_Container1 = NULL;
    ui_currentScene_icon = NULL;
    ui_currentScene_label = NULL;
    ui_Button1 = NULL;
    ui_nextScene_btn = NULL;
    ui_lights_toggle = NULL;
    ui_lights_switch = NULL;
    ui_lightsSwitch_text = NULL;
    ui_minis_overview = NULL;
    ui_minis_icon = NULL;
    ui_Container7 = NULL;
    ui_minisAmount_label = NULL;
    ui_minisAmount_text = NULL;

}
