// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_OVERVIEW_SCREEN_H
#define UI_OVERVIEW_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_overview_screen
extern void ui_overview_screen_screen_init(void);
extern void ui_overview_screen_screen_destroy(void);
extern lv_obj_t * ui_overview_screen;
extern lv_obj_t * ui_overviewBg_img;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_go_back_btn;
extern lv_obj_t * ui_header_icon;
extern lv_obj_t * ui_time_label;
extern lv_obj_t * ui_wifi_label;
extern lv_obj_t * ui_overviewTitle_text;
extern lv_obj_t * ui_navbar;
extern void ui_event_screenLights_btn(lv_event_t * e);
extern lv_obj_t * ui_screenLights_btn;
extern lv_obj_t * ui_Image7;
extern void ui_event_screenShelves_btn(lv_event_t * e);
extern lv_obj_t * ui_screenShelves_btn;
extern lv_obj_t * ui_Image2;
extern void ui_event_screenMinis_btn(lv_event_t * e);
extern lv_obj_t * ui_screenMinis_btn;
extern lv_obj_t * ui_minis_icon_40;
extern void ui_event_screen_settings_btn(lv_event_t * e);
extern lv_obj_t * ui_screen_settings_btn;
extern lv_obj_t * ui_screenSettings_btn;
extern lv_obj_t * ui_actions;
extern lv_obj_t * ui_scenes_section;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_previousScene_btn;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_currentScene_icon;
extern lv_obj_t * ui_currentScene_label;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_nextScene_btn;
extern lv_obj_t * ui_lights_toggle;
extern lv_obj_t * ui_lights_switch;
extern lv_obj_t * ui_lightsSwitch_text;
extern lv_obj_t * ui_minis_overview;
extern lv_obj_t * ui_minis_icon;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_minisAmount_label;
extern lv_obj_t * ui_minisAmount_text;
// CUSTOM VARIABLES
extern void ui_event_previousScene_btn(lv_event_t * e);
extern void ui_event_nextScene_btn(lv_event_t * e);
extern void ui_event_lights_switch(lv_event_t * e);
extern void ui_event_overview_screen_loaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

