// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_SETTINGS_SCREEN_H
#define UI_SETTINGS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings_screen
extern void ui_settings_screen_screen_init(void);
extern void ui_settings_screen_screen_destroy(void);
extern lv_obj_t * ui_settings_screen;
extern lv_obj_t * ui_header3;
extern lv_obj_t * ui_BodyContainer1;
extern void ui_event_recordBtn(lv_event_t * e);
extern lv_obj_t * ui_recordBtn;
extern lv_obj_t * ui_Label10;
extern void ui_event_resetCatalogueBtn(lv_event_t * e);
extern lv_obj_t * ui_resetCatalogueBtn;
extern lv_obj_t * ui_resetCatalogueLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

