// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

lv_obj_t * ui_shelves_screen = NULL;
lv_obj_t * ui_header2 = NULL;
lv_obj_t * ui_BodyContainerShelvesScreen = NULL;
lv_obj_t * ui_shelves_tabView = NULL;
lv_obj_t * ui_shelf1_tabContent = NULL;
lv_obj_t * ui_shelfTabBody_container = NULL;
lv_obj_t * ui_shelfInputs_container = NULL;
lv_obj_t * ui_shelfLocationsInput_container = NULL;
lv_obj_t * ui_hex_icon = NULL;
lv_obj_t * ui_inputUpDowmLocation = NULL;
lv_obj_t * ui_addLocation_btn = NULL;
lv_obj_t * ui_locationInShef_label = NULL;
lv_obj_t * ui_substractLocation_btn = NULL;
lv_obj_t * ui_shelfLedsInput_container = NULL;
lv_obj_t * ui_led_icon = NULL;
lv_obj_t * ui_inputUpDowmLocation1 = NULL;
lv_obj_t * ui_addLeds_btn = NULL;
lv_obj_t * ui_ledsInShef_label = NULL;
lv_obj_t * ui_substractLeds_btn = NULL;
lv_obj_t * ui_shelfLocationSelector_container = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_locationInShelf_text = NULL;
lv_obj_t * ui_shelfLedMapping_container = NULL;
lv_obj_t * ui_uiLedItemContainer = NULL;
lv_obj_t * ui_ledItemNoAssigned = NULL;
lv_obj_t * ui_ledItemIndex_text = NULL;
lv_obj_t * ui_shelfActions_container = NULL;
lv_obj_t * ui_autoMapAction_btn = NULL;
lv_obj_t * ui_autoMapAction_text = NULL;
lv_obj_t * ui_testLedsAction_btn = NULL;
lv_obj_t * ui_testLedsAction_text = NULL;
lv_obj_t * ui_saveLedsLocationAction_btn2 = NULL;
lv_obj_t * ui_saveLedsAction_text = NULL;
lv_obj_t * ui_shelfLedMapping_containerOverly = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_startLed_label = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_upDowmLocation_input = NULL;
lv_obj_t * ui_addLedsToLocation_btn = NULL;
lv_obj_t * ui_ledsInSection_inputValue = NULL;
lv_obj_t * ui_removeLedsToLocation_btn = NULL;
lv_obj_t * ui_endLed_label = NULL;
lv_obj_t * ui_ledsSectionActions_containerOverlay = NULL;
lv_obj_t * ui_closeAction_btn = NULL;
lv_obj_t * ui_closeAction_text = NULL;
lv_obj_t * ui_clearLedsLocationAction_btn = NULL;
lv_obj_t * ui_clearLedsAction_text = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_shelf1_tabContent(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        selectShelf(e);
    }
}

void ui_event_addLocation_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addLoactionToShelf(e);
    }
}

void ui_event_substractLocation_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        substractLocationFromShelf(e);
    }
}

void ui_event_addLeds_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addLedsToShelf(e);
    }
}

void ui_event_substractLeds_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        substractLedsFromShelf(e);
    }
}

void ui_event_locationInShelf_text(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        selectLocationToMap(e);
    }
}

void ui_event_ledItemNoAssigned(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_shelfLedMapping_containerOverly, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ledsSectionActions_containerOverlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_autoMapAction_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        autoMapLeds(e);
    }
}

void ui_event_testLedsAction_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        testLedsLocation(e);
    }
}

void ui_event_saveLedsLocationAction_btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clearAllLedsLocation(e);
    }
}

void ui_event_addLedsToLocation_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addLedsToSection(e);
    }
}

void ui_event_removeLedsToLocation_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        substractLedsToSection(e);
    }
}

void ui_event_closeAction_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cancelMapLeds(e);
        _ui_flag_modify(ui_ledsSectionActions_containerOverlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_shelfLedMapping_containerOverly, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_clearLedsLocationAction_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clearLedsLocation(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addShelf(e);
    }
}

// build funtions

void ui_shelves_screen_screen_init(void)
{
    ui_shelves_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_shelves_screen, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shelves_screen, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shelves_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header2 = ui_header2_create(ui_shelves_screen);
    lv_obj_set_x(ui_header2, 0);
    lv_obj_set_y(ui_header2, 0);

    ui_BodyContainerShelvesScreen = lv_obj_create(ui_shelves_screen);
    lv_obj_remove_style_all(ui_BodyContainerShelvesScreen);
    lv_obj_set_width(ui_BodyContainerShelvesScreen, lv_pct(98));
    lv_obj_set_height(ui_BodyContainerShelvesScreen, lv_pct(82));
    lv_obj_set_x(ui_BodyContainerShelvesScreen, 0);
    lv_obj_set_y(ui_BodyContainerShelvesScreen, -5);
    lv_obj_set_align(ui_BodyContainerShelvesScreen, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_BodyContainerShelvesScreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BodyContainerShelvesScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BodyContainerShelvesScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BodyContainerShelvesScreen, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BodyContainerShelvesScreen, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_BodyContainerShelvesScreen, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_BodyContainerShelvesScreen, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shelves_tabView = lv_tabview_create(ui_BodyContainerShelvesScreen, LV_DIR_LEFT, 40);
    lv_obj_set_width(ui_shelves_tabView, lv_pct(100));
    lv_obj_set_height(ui_shelves_tabView, lv_pct(100));
    lv_obj_set_x(ui_shelves_tabView, -124);
    lv_obj_set_y(ui_shelves_tabView, -9);
    lv_obj_set_align(ui_shelves_tabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelves_tabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shelves_tabView, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shelves_tabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_shelves_tabView, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_shelves_tabView, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_shelves_tabView), LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_shelves_tabView), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_shelves_tabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_shelves_tabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_shelves_tabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_shelves_tabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_shelves_tabView), LV_BORDER_SIDE_RIGHT,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(lv_tabview_get_tab_btns(ui_shelves_tabView), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(lv_tabview_get_tab_btns(ui_shelves_tabView), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_shelves_tabView), 4,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_shelves_tabView), lv_color_hex(0x00E4F6),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_shelves_tabView), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_shelves_tabView),  LV_PART_ITEMS | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_shelves_tabView),  LV_PART_ITEMS | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_shelves_tabView), 2,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_shelf1_tabContent = lv_tabview_add_tab(ui_shelves_tabView, "1");
    lv_obj_clear_flag(ui_shelf1_tabContent,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_shelf1_tabContent, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_shelf1_tabContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_shelf1_tabContent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_shelf1_tabContent, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_shelf1_tabContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_shelf1_tabContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_shelf1_tabContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_shelf1_tabContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shelfTabBody_container = lv_obj_create(ui_shelf1_tabContent);
    lv_obj_remove_style_all(ui_shelfTabBody_container);
    lv_obj_set_width(ui_shelfTabBody_container, lv_pct(100));
    lv_obj_set_height(ui_shelfTabBody_container, lv_pct(100));
    lv_obj_set_align(ui_shelfTabBody_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_shelfTabBody_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_shelfTabBody_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelfTabBody_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_shelfTabBody_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_shelfTabBody_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_shelfTabBody_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_shelfTabBody_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_shelfTabBody_container, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_shelfTabBody_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shelfInputs_container = lv_obj_create(ui_shelfTabBody_container);
    lv_obj_remove_style_all(ui_shelfInputs_container);
    lv_obj_set_width(ui_shelfInputs_container, lv_pct(100));
    lv_obj_set_height(ui_shelfInputs_container, lv_pct(20));
    lv_obj_set_align(ui_shelfInputs_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_shelfInputs_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_shelfInputs_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelfInputs_container,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_shelfLocationsInput_container = lv_obj_create(ui_shelfInputs_container);
    lv_obj_set_width(ui_shelfLocationsInput_container, lv_pct(50));
    lv_obj_set_height(ui_shelfLocationsInput_container, lv_pct(92));
    lv_obj_set_align(ui_shelfLocationsInput_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_shelfLocationsInput_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_shelfLocationsInput_container, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelfLocationsInput_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_shelfLocationsInput_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_shelfLocationsInput_container, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_shelfLocationsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hex_icon = lv_img_create(ui_shelfLocationsInput_container);
    lv_img_set_src(ui_hex_icon, &ui_img_hexagon_40dp_ffffff_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_hex_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hex_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_hex_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hex_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hex_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hex_icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_hex_icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);

    ui_inputUpDowmLocation = lv_obj_create(ui_shelfLocationsInput_container);
    lv_obj_remove_style_all(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_inputUpDowmLocation, lv_pct(75));
    lv_obj_set_height(ui_inputUpDowmLocation, lv_pct(85));
    lv_obj_set_align(ui_inputUpDowmLocation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_inputUpDowmLocation, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_inputUpDowmLocation, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_inputUpDowmLocation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_inputUpDowmLocation, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_inputUpDowmLocation, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_inputUpDowmLocation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputUpDowmLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_inputUpDowmLocation, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputUpDowmLocation, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addLocation_btn = lv_label_create(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_addLocation_btn, lv_pct(25));
    lv_obj_set_height(ui_addLocation_btn, lv_pct(100));
    lv_obj_set_align(ui_addLocation_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_addLocation_btn, "");
    lv_obj_set_style_bg_img_src(ui_addLocation_btn, &ui_img_add_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_addLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_addLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_addLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_addLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_addLocation_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_addLocation_btn, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_locationInShef_label = lv_label_create(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_locationInShef_label, lv_pct(50));
    lv_obj_set_height(ui_locationInShef_label, lv_pct(100));
    lv_obj_set_align(ui_locationInShef_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_locationInShef_label, "26");

    ui_substractLocation_btn = lv_label_create(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_substractLocation_btn, lv_pct(25));
    lv_obj_set_height(ui_substractLocation_btn, lv_pct(100));
    lv_obj_set_align(ui_substractLocation_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_substractLocation_btn, "");
    lv_obj_set_style_bg_img_src(ui_substractLocation_btn, &ui_img_remove_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_substractLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_substractLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_substractLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_substractLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_substractLocation_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_substractLocation_btn, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shelfLedsInput_container = lv_obj_create(ui_shelfInputs_container);
    lv_obj_set_width(ui_shelfLedsInput_container, lv_pct(50));
    lv_obj_set_height(ui_shelfLedsInput_container, lv_pct(92));
    lv_obj_set_align(ui_shelfLedsInput_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_shelfLedsInput_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_shelfLedsInput_container, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelfLedsInput_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_shelfLedsInput_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_shelfLedsInput_container, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_shelfLedsInput_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_led_icon = lv_img_create(ui_shelfLedsInput_container);
    lv_img_set_src(ui_led_icon, &ui_img_backlight_low_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_led_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_led_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_led_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_led_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_led_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_led_icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_led_icon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);

    ui_inputUpDowmLocation1 = lv_obj_create(ui_shelfLedsInput_container);
    lv_obj_remove_style_all(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_inputUpDowmLocation1, lv_pct(75));
    lv_obj_set_height(ui_inputUpDowmLocation1, lv_pct(85));
    lv_obj_set_align(ui_inputUpDowmLocation1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_inputUpDowmLocation1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_inputUpDowmLocation1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_inputUpDowmLocation1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_inputUpDowmLocation1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_inputUpDowmLocation1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_inputUpDowmLocation1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputUpDowmLocation1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_inputUpDowmLocation1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputUpDowmLocation1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addLeds_btn = lv_label_create(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_addLeds_btn, lv_pct(25));
    lv_obj_set_height(ui_addLeds_btn, lv_pct(100));
    lv_obj_set_align(ui_addLeds_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_addLeds_btn, "");
    lv_obj_set_style_bg_img_src(ui_addLeds_btn, &ui_img_add_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_addLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_addLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_addLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_addLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_addLeds_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_addLeds_btn, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledsInShef_label = lv_label_create(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_ledsInShef_label, lv_pct(50));
    lv_obj_set_height(ui_ledsInShef_label, lv_pct(100));
    lv_obj_set_align(ui_ledsInShef_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledsInShef_label, "160");

    ui_substractLeds_btn = lv_label_create(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_substractLeds_btn, lv_pct(25));
    lv_obj_set_height(ui_substractLeds_btn, lv_pct(100));
    lv_obj_set_align(ui_substractLeds_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_substractLeds_btn, "");
    lv_obj_set_style_bg_img_src(ui_substractLeds_btn, &ui_img_remove_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_substractLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_substractLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_substractLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_substractLeds_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_substractLeds_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_substractLeds_btn, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shelfLocationSelector_container = lv_obj_create(ui_shelfTabBody_container);
    lv_obj_remove_style_all(ui_shelfLocationSelector_container);
    lv_obj_set_width(ui_shelfLocationSelector_container, lv_pct(100));
    lv_obj_set_height(ui_shelfLocationSelector_container, lv_pct(30));
    lv_obj_set_align(ui_shelfLocationSelector_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_shelfLocationSelector_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_shelfLocationSelector_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelfLocationSelector_container,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_scroll_dir(ui_shelfLocationSelector_container, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_shelfLocationSelector_container, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_radius(ui_shelfLocationSelector_container, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_shelfLocationSelector_container, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_shelfLocationSelector_container, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_shelfLocationSelector_container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_shelfLocationSelector_container, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shelfLocationSelector_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_shelfLocationSelector_container, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shelfLocationSelector_container, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_shelfLocationSelector_container);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 70);
    lv_obj_set_height(ui_Container5, 56);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_img_src(ui_Container5, &ui_img_hexagon_72dp_00e4f6_fill0_wght400_grad0_opsz48_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Container5, lv_color_hex(0x6C7080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Container5, lv_color_hex(0x6C7080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(ui_Container5, LV_PART_MAIN | LV_STATE_EDITED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_Container5, LV_PART_MAIN | LV_STATE_EDITED, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Pink____________);
    ui_object_set_themeable_style_property(ui_Container5, LV_PART_MAIN | LV_STATE_EDITED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_Container5, LV_PART_MAIN | LV_STATE_EDITED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Pink____________);

    ui_locationInShelf_text = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_locationInShelf_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_locationInShelf_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_locationInShelf_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_locationInShelf_text, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_locationInShelf_text, "1");
    lv_obj_add_flag(ui_locationInShelf_text, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_locationInShelf_text,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_opa(ui_locationInShelf_text, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_locationInShelf_text, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_locationInShelf_text, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_locationInShelf_text, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_locationInShelf_text, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_align(ui_locationInShelf_text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_opa(ui_locationInShelf_text, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    ui_object_set_themeable_style_property(ui_locationInShelf_text, LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_locationInShelf_text, LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_pad_left(ui_locationInShelf_text, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_locationInShelf_text, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_locationInShelf_text, 12, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_locationInShelf_text, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_shelfLedMapping_container = lv_obj_create(ui_shelfTabBody_container);
    lv_obj_remove_style_all(ui_shelfLedMapping_container);
    lv_obj_set_width(ui_shelfLedMapping_container, lv_pct(100));
    lv_obj_set_height(ui_shelfLedMapping_container, lv_pct(30));
    lv_obj_set_align(ui_shelfLedMapping_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_shelfLedMapping_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_shelfLedMapping_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelfLedMapping_container,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_scroll_dir(ui_shelfLedMapping_container, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_shelfLedMapping_container, LV_SCROLL_SNAP_START);
    lv_obj_set_style_radius(ui_shelfLedMapping_container, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_shelfLedMapping_container, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_shelfLedMapping_container, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_shelfLedMapping_container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_shelfLedMapping_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_shelfLedMapping_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer = lv_obj_create(ui_shelfLedMapping_container);
    lv_obj_remove_style_all(ui_uiLedItemContainer);
    lv_obj_set_height(ui_uiLedItemContainer, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledItemNoAssigned = lv_obj_create(ui_uiLedItemContainer);
    lv_obj_set_width(ui_ledItemNoAssigned, 16);
    lv_obj_set_height(ui_ledItemNoAssigned, lv_pct(80));
    lv_obj_set_align(ui_ledItemNoAssigned, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ledItemNoAssigned, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ledItemNoAssigned, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ledItemNoAssigned, lv_color_hex(0x17569A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ledItemNoAssigned, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ledItemNoAssigned, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ledItemNoAssigned, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ledItemNoAssigned, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledItemIndex_text = lv_label_create(ui_uiLedItemContainer);
    lv_obj_set_width(ui_ledItemIndex_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledItemIndex_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ledItemIndex_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledItemIndex_text, "10");
    lv_obj_set_style_text_color(ui_ledItemIndex_text, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ledItemIndex_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shelfActions_container = lv_obj_create(ui_shelfTabBody_container);
    lv_obj_remove_style_all(ui_shelfActions_container);
    lv_obj_set_width(ui_shelfActions_container, lv_pct(100));
    lv_obj_set_height(ui_shelfActions_container, lv_pct(20));
    lv_obj_set_align(ui_shelfActions_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_shelfActions_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_shelfActions_container, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_shelfActions_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autoMapAction_btn = lv_btn_create(ui_shelfActions_container);
    lv_obj_set_width(ui_autoMapAction_btn, lv_pct(30));
    lv_obj_set_height(ui_autoMapAction_btn, lv_pct(85));
    lv_obj_set_align(ui_autoMapAction_btn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_autoMapAction_btn,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_autoMapAction_btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_autoMapAction_btn, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_autoMapAction_btn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_autoMapAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_autoMapAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_autoMapAction_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_autoMapAction_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autoMapAction_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_autoMapAction_btn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autoMapAction_text = lv_label_create(ui_autoMapAction_btn);
    lv_obj_set_width(ui_autoMapAction_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autoMapAction_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_autoMapAction_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_autoMapAction_text, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_autoMapAction_text, "AUTO");
    lv_obj_add_flag(ui_autoMapAction_text, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_autoMapAction_text,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_testLedsAction_btn = lv_btn_create(ui_shelfActions_container);
    lv_obj_set_width(ui_testLedsAction_btn, lv_pct(30));
    lv_obj_set_height(ui_testLedsAction_btn, lv_pct(85));
    lv_obj_set_align(ui_testLedsAction_btn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_testLedsAction_btn,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_testLedsAction_btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_testLedsAction_btn, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_testLedsAction_btn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_testLedsAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_testLedsAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_testLedsAction_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_testLedsAction_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_testLedsAction_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_testLedsAction_btn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_testLedsAction_text = lv_label_create(ui_testLedsAction_btn);
    lv_obj_set_width(ui_testLedsAction_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_testLedsAction_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_testLedsAction_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_testLedsAction_text, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_testLedsAction_text, "TEST");

    ui_saveLedsLocationAction_btn2 = lv_btn_create(ui_shelfActions_container);
    lv_obj_set_width(ui_saveLedsLocationAction_btn2, lv_pct(30));
    lv_obj_set_height(ui_saveLedsLocationAction_btn2, lv_pct(85));
    lv_obj_set_align(ui_saveLedsLocationAction_btn2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_saveLedsLocationAction_btn2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_saveLedsLocationAction_btn2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_saveLedsLocationAction_btn2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_saveLedsLocationAction_btn2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_saveLedsLocationAction_btn2, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveLedsLocationAction_btn2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_saveLedsLocationAction_btn2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_saveLedsLocationAction_btn2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_saveLedsLocationAction_btn2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_saveLedsLocationAction_btn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_saveLedsLocationAction_btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_saveLedsLocationAction_btn2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveLedsAction_text = lv_label_create(ui_saveLedsLocationAction_btn2);
    lv_obj_set_width(ui_saveLedsAction_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveLedsAction_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_saveLedsAction_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_saveLedsAction_text, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_saveLedsAction_text, "CLEAR ALL");

    ui_shelfLedMapping_containerOverly = lv_obj_create(ui_shelf1_tabContent);
    lv_obj_set_height(ui_shelfLedMapping_containerOverly, 61);
    lv_obj_set_width(ui_shelfLedMapping_containerOverly, lv_pct(100));
    lv_obj_set_align(ui_shelfLedMapping_containerOverly, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_shelfLedMapping_containerOverly, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_shelfLedMapping_containerOverly, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_shelfLedMapping_containerOverly, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_shelfLedMapping_containerOverly,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_shelfLedMapping_containerOverly, lv_color_hex(0x101629), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shelfLedMapping_containerOverly, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_shelfLedMapping_containerOverly, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_shelfLedMapping_containerOverly, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_shelfLedMapping_containerOverly, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_shelfLedMapping_containerOverly);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_height(ui_Container6, 53);
    lv_obj_set_width(ui_Container6, lv_pct(103));
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_Container6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container6, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startLed_label = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_startLed_label, 72);
    lv_obj_set_height(ui_startLed_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_startLed_label, 0);
    lv_obj_set_y(ui_startLed_label, 10);
    lv_obj_set_align(ui_startLed_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startLed_label, "12");
    ui_object_set_themeable_style_property(ui_startLed_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_startLed_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Pink____________);
    lv_obj_set_style_text_letter_space(ui_startLed_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_startLed_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 219);
    lv_obj_set_height(ui_Container8, 60);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_upDowmLocation_input = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_upDowmLocation_input);
    lv_obj_set_width(ui_upDowmLocation_input, lv_pct(75));
    lv_obj_set_height(ui_upDowmLocation_input, lv_pct(70));
    lv_obj_set_align(ui_upDowmLocation_input, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_upDowmLocation_input, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_upDowmLocation_input, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_upDowmLocation_input, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_upDowmLocation_input, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_upDowmLocation_input, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_upDowmLocation_input, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_upDowmLocation_input, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_upDowmLocation_input, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_upDowmLocation_input, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_upDowmLocation_input, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_upDowmLocation_input, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_addLedsToLocation_btn = lv_label_create(ui_upDowmLocation_input);
    lv_obj_set_width(ui_addLedsToLocation_btn, lv_pct(25));
    lv_obj_set_height(ui_addLedsToLocation_btn, lv_pct(100));
    lv_obj_set_align(ui_addLedsToLocation_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_addLedsToLocation_btn, "");
    lv_obj_set_style_bg_img_src(ui_addLedsToLocation_btn, &ui_img_add_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_addLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_addLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_addLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_addLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_addLedsToLocation_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_addLedsToLocation_btn, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledsInSection_inputValue = lv_label_create(ui_upDowmLocation_input);
    lv_obj_set_width(ui_ledsInSection_inputValue, lv_pct(50));
    lv_obj_set_height(ui_ledsInSection_inputValue, lv_pct(100));
    lv_obj_set_align(ui_ledsInSection_inputValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledsInSection_inputValue, "6");

    ui_removeLedsToLocation_btn = lv_label_create(ui_upDowmLocation_input);
    lv_obj_set_width(ui_removeLedsToLocation_btn, lv_pct(25));
    lv_obj_set_height(ui_removeLedsToLocation_btn, lv_pct(100));
    lv_obj_set_align(ui_removeLedsToLocation_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_removeLedsToLocation_btn, "");
    lv_obj_set_style_bg_img_src(ui_removeLedsToLocation_btn, &ui_img_remove_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_removeLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_removeLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_removeLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_removeLedsToLocation_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_removeLedsToLocation_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_removeLedsToLocation_btn, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_endLed_label = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_endLed_label, 72);
    lv_obj_set_height(ui_endLed_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_endLed_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_endLed_label, "17");
    lv_obj_set_style_text_color(ui_endLed_label, lv_color_hex(0xF6972E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_endLed_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_endLed_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_endLed_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledsSectionActions_containerOverlay = lv_obj_create(ui_shelf1_tabContent);
    lv_obj_remove_style_all(ui_ledsSectionActions_containerOverlay);
    lv_obj_set_width(ui_ledsSectionActions_containerOverlay, lv_pct(100));
    lv_obj_set_height(ui_ledsSectionActions_containerOverlay, lv_pct(18));
    lv_obj_set_align(ui_ledsSectionActions_containerOverlay, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ledsSectionActions_containerOverlay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ledsSectionActions_containerOverlay, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ledsSectionActions_containerOverlay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ledsSectionActions_containerOverlay,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ledsSectionActions_containerOverlay, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ledsSectionActions_containerOverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeAction_btn = lv_btn_create(ui_ledsSectionActions_containerOverlay);
    lv_obj_set_width(ui_closeAction_btn, lv_pct(48));
    lv_obj_set_height(ui_closeAction_btn, lv_pct(90));
    lv_obj_set_align(ui_closeAction_btn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_closeAction_btn,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_closeAction_btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_closeAction_btn, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_closeAction_btn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_closeAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_closeAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_closeAction_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_closeAction_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_closeAction_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_closeAction_btn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeAction_text = lv_label_create(ui_closeAction_btn);
    lv_obj_set_width(ui_closeAction_text, 40);
    lv_obj_set_height(ui_closeAction_text, 40);
    lv_obj_set_align(ui_closeAction_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_closeAction_text, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_closeAction_text, "");
    lv_obj_clear_flag(ui_closeAction_text,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_img_src(ui_closeAction_text, &ui_img_close_40dp_ea33f7_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clearLedsLocationAction_btn = lv_btn_create(ui_ledsSectionActions_containerOverlay);
    lv_obj_set_width(ui_clearLedsLocationAction_btn, lv_pct(48));
    lv_obj_set_height(ui_clearLedsLocationAction_btn, lv_pct(90));
    lv_obj_set_align(ui_clearLedsLocationAction_btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_clearLedsLocationAction_btn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_clearLedsLocationAction_btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clearLedsLocationAction_btn,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_clearLedsLocationAction_btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clearLedsLocationAction_btn, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clearLedsLocationAction_btn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_clearLedsLocationAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_clearLedsLocationAction_btn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_clearLedsLocationAction_btn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_clearLedsLocationAction_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clearLedsLocationAction_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clearLedsLocationAction_btn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clearLedsAction_text = lv_label_create(ui_clearLedsLocationAction_btn);
    lv_obj_set_width(ui_clearLedsAction_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clearLedsAction_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clearLedsAction_text, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_clearLedsAction_text, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_clearLedsAction_text, "CLEAR");

    ui_Button2 = lv_btn_create(ui_shelves_screen);
    lv_obj_set_width(ui_Button2, 40);
    lv_obj_set_height(ui_Button2, 34);
    lv_obj_set_x(ui_Button2, 100);
    lv_obj_set_y(ui_Button2, -139);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_font(ui_Button2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "+");
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_addLocation_btn, ui_event_addLocation_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_substractLocation_btn, ui_event_substractLocation_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_addLeds_btn, ui_event_addLeds_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_substractLeds_btn, ui_event_substractLeds_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_locationInShelf_text, ui_event_locationInShelf_text, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledItemNoAssigned, ui_event_ledItemNoAssigned, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_autoMapAction_btn, ui_event_autoMapAction_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_testLedsAction_btn, ui_event_testLedsAction_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveLedsLocationAction_btn2, ui_event_saveLedsLocationAction_btn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_addLedsToLocation_btn, ui_event_addLedsToLocation_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_removeLedsToLocation_btn, ui_event_removeLedsToLocation_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_closeAction_btn, ui_event_closeAction_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clearLedsLocationAction_btn, ui_event_clearLedsLocationAction_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_shelf1_tabContent, ui_event_shelf1_tabContent, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_shelves_screen, ui_event_shelves_screen_loaded, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(ui_shelves_screen, ui_event_shelves_screen_unloaded, LV_EVENT_SCREEN_UNLOADED, NULL);

}

void ui_shelves_screen_screen_destroy(void)
{
    if(ui_shelves_screen) lv_obj_del(ui_shelves_screen);

    // NULL screen variables
    ui_shelves_screen = NULL;
    ui_header2 = NULL;
    ui_BodyContainerShelvesScreen = NULL;
    ui_shelves_tabView = NULL;
    ui_shelf1_tabContent = NULL;
    ui_shelfTabBody_container = NULL;
    ui_shelfInputs_container = NULL;
    ui_shelfLocationsInput_container = NULL;
    ui_hex_icon = NULL;
    ui_inputUpDowmLocation = NULL;
    ui_addLocation_btn = NULL;
    ui_locationInShef_label = NULL;
    ui_substractLocation_btn = NULL;
    ui_shelfLedsInput_container = NULL;
    ui_led_icon = NULL;
    ui_inputUpDowmLocation1 = NULL;
    ui_addLeds_btn = NULL;
    ui_ledsInShef_label = NULL;
    ui_substractLeds_btn = NULL;
    ui_shelfLocationSelector_container = NULL;
    ui_Container5 = NULL;
    ui_locationInShelf_text = NULL;
    ui_shelfLedMapping_container = NULL;
    ui_uiLedItemContainer = NULL;
    ui_ledItemNoAssigned = NULL;
    ui_ledItemIndex_text = NULL;
    ui_shelfActions_container = NULL;
    ui_autoMapAction_btn = NULL;
    ui_autoMapAction_text = NULL;
    ui_testLedsAction_btn = NULL;
    ui_testLedsAction_text = NULL;
    ui_saveLedsLocationAction_btn2 = NULL;
    ui_saveLedsAction_text = NULL;
    ui_shelfLedMapping_containerOverly = NULL;
    ui_Container6 = NULL;
    ui_startLed_label = NULL;
    ui_Container8 = NULL;
    ui_upDowmLocation_input = NULL;
    ui_addLedsToLocation_btn = NULL;
    ui_ledsInSection_inputValue = NULL;
    ui_removeLedsToLocation_btn = NULL;
    ui_endLed_label = NULL;
    ui_ledsSectionActions_containerOverlay = NULL;
    ui_closeAction_btn = NULL;
    ui_closeAction_text = NULL;
    ui_clearLedsLocationAction_btn = NULL;
    ui_clearLedsAction_text = NULL;
    ui_Button2 = NULL;
    ui_Label1 = NULL;

}
