// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_SHELVES_SCREEN_H
#define UI_SHELVES_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_shelves_screen
extern void ui_shelves_screen_screen_init(void);
extern void ui_shelves_screen_screen_destroy(void);
extern void ui_event_shelves_screen_loaded(lv_event_t * e);
extern void ui_event_shelves_screen_unloaded(lv_event_t * e);
extern lv_obj_t * ui_shelves_screen;
extern lv_obj_t * ui_header2;
extern lv_obj_t * ui_BodyContainerShelvesScreen;
extern lv_obj_t * ui_shelves_tabView;
extern void ui_event_shelf1_tabContent(lv_event_t * e);
extern lv_obj_t * ui_shelf1_tabContent;
extern lv_obj_t * ui_shelfTabBody_container;
extern lv_obj_t * ui_shelfInputs_container;
extern lv_obj_t * ui_shelfLocationsInput_container;
extern lv_obj_t * ui_hex_icon;
extern lv_obj_t * ui_inputUpDowmLocation;
extern void ui_event_addLocation_btn(lv_event_t * e);
extern lv_obj_t * ui_addLocation_btn;
extern lv_obj_t * ui_locationInShef_label;
extern void ui_event_substractLocation_btn(lv_event_t * e);
extern lv_obj_t * ui_substractLocation_btn;
extern lv_obj_t * ui_shelfLedsInput_container;
extern lv_obj_t * ui_led_icon;
extern lv_obj_t * ui_inputUpDowmLocation1;
extern void ui_event_addLeds_btn(lv_event_t * e);
extern lv_obj_t * ui_addLeds_btn;
extern lv_obj_t * ui_ledsInShef_label;
extern void ui_event_substractLeds_btn(lv_event_t * e);
extern lv_obj_t * ui_substractLeds_btn;
extern lv_obj_t * ui_shelfLocationSelector_container;
extern lv_obj_t * ui_Container5;
extern void ui_event_locationInShelf_text(lv_event_t * e);
extern lv_obj_t * ui_locationInShelf_text;
extern lv_obj_t * ui_shelfLedMapping_container;
extern lv_obj_t * ui_uiLedItemContainer;
extern void ui_event_ledItemNoAssigned(lv_event_t * e);
extern lv_obj_t * ui_ledItemNoAssigned;
extern lv_obj_t * ui_ledItemIndex_text;
extern lv_obj_t * ui_shelfActions_container;
extern void ui_event_autoMapAction_btn(lv_event_t * e);
extern lv_obj_t * ui_autoMapAction_btn;
extern lv_obj_t * ui_autoMapAction_text;
extern void ui_event_testLedsAction_btn(lv_event_t * e);
extern lv_obj_t * ui_testLedsAction_btn;
extern lv_obj_t * ui_testLedsAction_text;
extern void ui_event_saveLedsLocationAction_btn2(lv_event_t * e);
extern lv_obj_t * ui_saveLedsLocationAction_btn2;
extern lv_obj_t * ui_saveLedsAction_text;
extern lv_obj_t * ui_shelfLedMapping_containerOverly;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_startLed_label;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_upDowmLocation_input;
extern void ui_event_addLedsToLocation_btn(lv_event_t * e);
extern lv_obj_t * ui_addLedsToLocation_btn;
extern lv_obj_t * ui_ledsInSection_inputValue;
extern void ui_event_removeLedsToLocation_btn(lv_event_t * e);
extern lv_obj_t * ui_removeLedsToLocation_btn;
extern lv_obj_t * ui_endLed_label;
extern lv_obj_t * ui_ledsSectionActions_containerOverlay;
extern void ui_event_closeAction_btn(lv_event_t * e);
extern lv_obj_t * ui_closeAction_btn;
extern lv_obj_t * ui_closeAction_text;
extern void ui_event_clearLedsLocationAction_btn(lv_event_t * e);
extern lv_obj_t * ui_clearLedsLocationAction_btn;
extern lv_obj_t * ui_clearLedsAction_text;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

