// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

lv_obj_t * ui_SETTINGS = NULL;
lv_obj_t * ui_header3 = NULL;
lv_obj_t * ui_BodyContainer1 = NULL;
lv_obj_t * ui_recordBtn = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions
void ui_event_recordBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        recordTestCallback(e);
    }
}

// build funtions

void ui_SETTINGS_screen_init(void)
{
    ui_SETTINGS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETTINGS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SETTINGS, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SETTINGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header3 = ui_header2_create(ui_SETTINGS);
    lv_obj_set_x(ui_header3, 0);
    lv_obj_set_y(ui_header3, 0);

    lv_img_set_src(ui_comp_get_child(ui_header3, UI_COMP_HEADER2_CONTAINER2_HEADER_ICON2),
                   &ui_img_settings_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);

    lv_label_set_text(ui_comp_get_child(ui_header3, UI_COMP_HEADER2_CONTAINER2_TITLE_SHELVES), "SETTINGS");

    ui_BodyContainer1 = ui_BodyContainer_create(ui_SETTINGS);
    lv_obj_set_x(ui_BodyContainer1, 0);
    lv_obj_set_y(ui_BodyContainer1, -15);

    ui_recordBtn = lv_btn_create(ui_SETTINGS);
    lv_obj_set_width(ui_recordBtn, 246);
    lv_obj_set_height(ui_recordBtn, 60);
    lv_obj_set_align(ui_recordBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_recordBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_recordBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_recordBtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_recordBtn, lv_color_hex(0x531F71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_recordBtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_recordBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_recordBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_recordBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_recordBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_recordBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_recordBtn);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "RECORD TEST");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_recordBtn, ui_event_recordBtn, LV_EVENT_ALL, NULL);

}

void ui_SETTINGS_screen_destroy(void)
{
    if(ui_SETTINGS) lv_obj_del(ui_SETTINGS);

    // NULL screen variables
    ui_SETTINGS = NULL;
    ui_header3 = NULL;
    ui_BodyContainer1 = NULL;
    ui_recordBtn = NULL;
    ui_Label10 = NULL;

}
