// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#include "../ui.h"

lv_obj_t * ui_SHELVES_SCREEN = NULL;
lv_obj_t * ui_header2 = NULL;
lv_obj_t * ui_BodyContainerShelvesScreen = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_SHELF_1 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_uiShelfInputsContainer = NULL;
lv_obj_t * ui_uiShelfLocationsInputContainer = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_inputUpDowmLocation = NULL;
lv_obj_t * ui_uiInputBtnUp = NULL;
lv_obj_t * ui_uiInputUpDownValue = NULL;
lv_obj_t * ui_uiInputBtnDown = NULL;
lv_obj_t * ui_uiShelfLedsInputContainer = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_inputUpDowmLocation1 = NULL;
lv_obj_t * ui_uiInputBtnUp1 = NULL;
lv_obj_t * ui_uiInputUpDownValue1 = NULL;
lv_obj_t * ui_uiInputBtnDown1 = NULL;
lv_obj_t * ui_uiShelfLocationSelectorContainer = NULL;
lv_obj_t * ui_uiShelfPositionItem = NULL;
lv_obj_t * ui_uiShelfPositionItem1 = NULL;
lv_obj_t * ui_uiShelfLedMappingContainer = NULL;
lv_obj_t * ui_uiLedItemContainer = NULL;
lv_obj_t * ui_uiLedItem = NULL;
lv_obj_t * ui_uiLedItemLabel = NULL;
lv_obj_t * ui_uiLedItemContainer1 = NULL;
lv_obj_t * ui_uiLedItem1 = NULL;
lv_obj_t * ui_uiLedItemLabel1 = NULL;
lv_obj_t * ui_uiLedItemContainer2 = NULL;
lv_obj_t * ui_uiLedItem2 = NULL;
lv_obj_t * ui_uiLedItemLabel2 = NULL;
lv_obj_t * ui_uiLedItemContainer4 = NULL;
lv_obj_t * ui_uiLedItem4 = NULL;
lv_obj_t * ui_uiLedItemLabel4 = NULL;
lv_obj_t * ui_uiLedItemContainer5 = NULL;
lv_obj_t * ui_uiLedItem5 = NULL;
lv_obj_t * ui_uiLedItemLabel5 = NULL;
lv_obj_t * ui_uiLedItemContainer3 = NULL;
lv_obj_t * ui_uiLedItem3 = NULL;
lv_obj_t * ui_uiLedItemLabel3 = NULL;
lv_obj_t * ui_uiLedItemContainer12 = NULL;
lv_obj_t * ui_uiLedItem12 = NULL;
lv_obj_t * ui_uiLedItemLabel12 = NULL;
lv_obj_t * ui_uiLedItemContainer8 = NULL;
lv_obj_t * ui_uiLedItem8 = NULL;
lv_obj_t * ui_uiLedItemLabel8 = NULL;
lv_obj_t * ui_uiLedItemContainer9 = NULL;
lv_obj_t * ui_uiLedItem9 = NULL;
lv_obj_t * ui_uiLedItemLabel9 = NULL;
lv_obj_t * ui_uiLedItemContainer10 = NULL;
lv_obj_t * ui_uiLedItem10 = NULL;
lv_obj_t * ui_uiLedItemLabel10 = NULL;
lv_obj_t * ui_uiLedItemContainer11 = NULL;
lv_obj_t * ui_uiLedItem11 = NULL;
lv_obj_t * ui_uiLedItemLabel11 = NULL;
lv_obj_t * ui_uiShelfActionsContainer = NULL;
lv_obj_t * ui_uiShelfLedMappingContainerOverly = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_startLabel = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_inputUpDowmLocation3 = NULL;
lv_obj_t * ui_uiInputBtnUp3 = NULL;
lv_obj_t * ui_uiInputUpDownTotalLedsValue = NULL;
lv_obj_t * ui_uiInputBtnDown3 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_startLabel1 = NULL;
lv_obj_t * ui_SHELF_2 = NULL;
lv_obj_t * ui_SHELF_3 = NULL;
lv_obj_t * ui_SHELF_4 = NULL;
lv_obj_t * ui_SHELF_5 = NULL;
lv_obj_t * ui_ADD_SHELF = NULL;
// event funtions

// build funtions

void ui_SHELVES_SCREEN_screen_init(void)
{
    ui_SHELVES_SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SHELVES_SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SHELVES_SCREEN, lv_color_hex(0x05050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SHELVES_SCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header2 = ui_header2_create(ui_SHELVES_SCREEN);
    lv_obj_set_x(ui_header2, 0);
    lv_obj_set_y(ui_header2, 0);

    ui_BodyContainerShelvesScreen = lv_obj_create(ui_SHELVES_SCREEN);
    lv_obj_remove_style_all(ui_BodyContainerShelvesScreen);
    lv_obj_set_width(ui_BodyContainerShelvesScreen, lv_pct(98));
    lv_obj_set_height(ui_BodyContainerShelvesScreen, lv_pct(82));
    lv_obj_set_x(ui_BodyContainerShelvesScreen, 0);
    lv_obj_set_y(ui_BodyContainerShelvesScreen, -5);
    lv_obj_set_align(ui_BodyContainerShelvesScreen, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_BodyContainerShelvesScreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BodyContainerShelvesScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BodyContainerShelvesScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BodyContainerShelvesScreen, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BodyContainerShelvesScreen, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_BodyContainerShelvesScreen, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_BodyContainerShelvesScreen, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BodyContainerShelvesScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_BodyContainerShelvesScreen, LV_DIR_LEFT, 40);
    lv_obj_set_width(ui_TabView1, lv_pct(100));
    lv_obj_set_height(ui_TabView1, lv_pct(100));
    lv_obj_set_x(ui_TabView1, -124);
    lv_obj_set_y(ui_TabView1, -9);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TabView1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_TabView1), LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Card____________);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_Card____________);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_TabView1), LV_BORDER_SIDE_RIGHT,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(lv_tabview_get_tab_btns(ui_TabView1), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(lv_tabview_get_tab_btns(ui_TabView1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView1), 4,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x00E4F6),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_ITEMS | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1),  LV_PART_ITEMS | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_TabView1), 2,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_SHELF_1 = lv_tabview_add_tab(ui_TabView1, "1");
    lv_obj_clear_flag(ui_SHELF_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_SHELF_1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SHELF_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_SHELF_1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_SHELF_1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SHELF_1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SHELF_1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SHELF_1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SHELF_1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_SHELF_1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, lv_pct(100));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiShelfInputsContainer = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_uiShelfInputsContainer);
    lv_obj_set_width(ui_uiShelfInputsContainer, lv_pct(100));
    lv_obj_set_height(ui_uiShelfInputsContainer, lv_pct(20));
    lv_obj_set_align(ui_uiShelfInputsContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiShelfInputsContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiShelfInputsContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiShelfInputsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiShelfLocationsInputContainer = lv_obj_create(ui_uiShelfInputsContainer);
    lv_obj_set_width(ui_uiShelfLocationsInputContainer, lv_pct(50));
    lv_obj_set_height(ui_uiShelfLocationsInputContainer, lv_pct(100));
    lv_obj_set_align(ui_uiShelfLocationsInputContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiShelfLocationsInputContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiShelfLocationsInputContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiShelfLocationsInputContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiShelfLocationsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiShelfLocationsInputContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiShelfLocationsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfLocationsInputContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_uiShelfLocationsInputContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_uiShelfLocationsInputContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiShelfLocationsInputContainer, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uiShelfLocationsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiShelfLocationsInputContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiShelfLocationsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiShelfLocationsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_uiShelfLocationsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uiShelfLocationsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_uiShelfLocationsInputContainer);
    lv_img_set_src(ui_Image1, &ui_img_hexagon_40dp_ffffff_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Image1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_Image1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);

    ui_inputUpDowmLocation = lv_obj_create(ui_uiShelfLocationsInputContainer);
    lv_obj_remove_style_all(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_inputUpDowmLocation, lv_pct(75));
    lv_obj_set_height(ui_inputUpDowmLocation, lv_pct(100));
    lv_obj_set_align(ui_inputUpDowmLocation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_inputUpDowmLocation, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_inputUpDowmLocation, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_inputUpDowmLocation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_inputUpDowmLocation, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_inputUpDowmLocation, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_inputUpDowmLocation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputUpDowmLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_inputUpDowmLocation, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputUpDowmLocation, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiInputBtnUp = lv_label_create(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_uiInputBtnUp, lv_pct(25));
    lv_obj_set_height(ui_uiInputBtnUp, lv_pct(100));
    lv_obj_set_align(ui_uiInputBtnUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputBtnUp, "");
    lv_obj_set_style_bg_img_src(ui_uiInputBtnUp, &ui_img_add_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiInputBtnUp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiInputBtnUp, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiInputUpDownValue = lv_label_create(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_uiInputUpDownValue, lv_pct(50));
    lv_obj_set_height(ui_uiInputUpDownValue, lv_pct(100));
    lv_obj_set_align(ui_uiInputUpDownValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputUpDownValue, "26");

    ui_uiInputBtnDown = lv_label_create(ui_inputUpDowmLocation);
    lv_obj_set_width(ui_uiInputBtnDown, lv_pct(25));
    lv_obj_set_height(ui_uiInputBtnDown, lv_pct(100));
    lv_obj_set_align(ui_uiInputBtnDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputBtnDown, "");
    lv_obj_set_style_bg_img_src(ui_uiInputBtnDown, &ui_img_remove_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiInputBtnDown, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiInputBtnDown, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiShelfLedsInputContainer = lv_obj_create(ui_uiShelfInputsContainer);
    lv_obj_set_width(ui_uiShelfLedsInputContainer, lv_pct(50));
    lv_obj_set_height(ui_uiShelfLedsInputContainer, lv_pct(100));
    lv_obj_set_align(ui_uiShelfLedsInputContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiShelfLedsInputContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiShelfLedsInputContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiShelfLedsInputContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiShelfLedsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiShelfLedsInputContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiShelfLedsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfLedsInputContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_uiShelfLedsInputContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_uiShelfLedsInputContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiShelfLedsInputContainer, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uiShelfLedsInputContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiShelfLedsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiShelfLedsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiShelfLedsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_uiShelfLedsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uiShelfLedsInputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_uiShelfLedsInputContainer);
    lv_img_set_src(ui_Image6, &ui_img_backlight_low_40dp_00e4f6_fill0_wght400_grad0_opsz40_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Image6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_Image6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);

    ui_inputUpDowmLocation1 = lv_obj_create(ui_uiShelfLedsInputContainer);
    lv_obj_remove_style_all(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_inputUpDowmLocation1, lv_pct(75));
    lv_obj_set_height(ui_inputUpDowmLocation1, lv_pct(100));
    lv_obj_set_align(ui_inputUpDowmLocation1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_inputUpDowmLocation1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_inputUpDowmLocation1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_inputUpDowmLocation1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_inputUpDowmLocation1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_inputUpDowmLocation1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_inputUpDowmLocation1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputUpDowmLocation1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_inputUpDowmLocation1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputUpDowmLocation1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiInputBtnUp1 = lv_label_create(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_uiInputBtnUp1, lv_pct(25));
    lv_obj_set_height(ui_uiInputBtnUp1, lv_pct(100));
    lv_obj_set_align(ui_uiInputBtnUp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputBtnUp1, "");
    lv_obj_set_style_bg_img_src(ui_uiInputBtnUp1, &ui_img_add_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiInputBtnUp1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiInputBtnUp1, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiInputUpDownValue1 = lv_label_create(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_uiInputUpDownValue1, lv_pct(50));
    lv_obj_set_height(ui_uiInputUpDownValue1, lv_pct(100));
    lv_obj_set_align(ui_uiInputUpDownValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputUpDownValue1, "160");

    ui_uiInputBtnDown1 = lv_label_create(ui_inputUpDowmLocation1);
    lv_obj_set_width(ui_uiInputBtnDown1, lv_pct(25));
    lv_obj_set_height(ui_uiInputBtnDown1, lv_pct(100));
    lv_obj_set_align(ui_uiInputBtnDown1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputBtnDown1, "");
    lv_obj_set_style_bg_img_src(ui_uiInputBtnDown1, &ui_img_remove_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiInputBtnDown1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiInputBtnDown1, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiShelfLocationSelectorContainer = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_uiShelfLocationSelectorContainer);
    lv_obj_set_width(ui_uiShelfLocationSelectorContainer, lv_pct(100));
    lv_obj_set_height(ui_uiShelfLocationSelectorContainer, lv_pct(30));
    lv_obj_set_align(ui_uiShelfLocationSelectorContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiShelfLocationSelectorContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiShelfLocationSelectorContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiShelfLocationSelectorContainer,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_uiShelfLocationSelectorContainer, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_uiShelfLocationSelectorContainer, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_uiShelfLocationSelectorContainer, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_radius(ui_uiShelfLocationSelectorContainer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfLocationSelectorContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiShelfLocationSelectorContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_uiShelfLocationSelectorContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_uiShelfLocationSelectorContainer, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiShelfLocationSelectorContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uiShelfLocationSelectorContainer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiShelfLocationSelectorContainer, &lv_font_montserrat_32,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiShelfPositionItem = lv_label_create(ui_uiShelfLocationSelectorContainer);
    lv_obj_set_width(ui_uiShelfPositionItem, lv_pct(20));
    lv_obj_set_height(ui_uiShelfPositionItem, lv_pct(100));
    lv_obj_set_x(ui_uiShelfPositionItem, -87);
    lv_obj_set_y(ui_uiShelfPositionItem, -14);
    lv_obj_set_align(ui_uiShelfPositionItem, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_uiShelfPositionItem, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_uiShelfPositionItem, "1");
    lv_obj_add_state(ui_uiShelfPositionItem, LV_STATE_FOCUSED);       /// States
    lv_obj_clear_flag(ui_uiShelfPositionItem,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_src(ui_uiShelfPositionItem, &ui_img_hexagon_72dp_00e4f6_fill0_wght400_grad0_opsz48_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_uiShelfPositionItem, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_pad_left(ui_uiShelfPositionItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiShelfPositionItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiShelfPositionItem, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiShelfPositionItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_align(ui_uiShelfPositionItem, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_opa(ui_uiShelfPositionItem, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem, LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_pad_left(ui_uiShelfPositionItem, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_uiShelfPositionItem, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_uiShelfPositionItem, 12, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_uiShelfPositionItem, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_uiShelfPositionItem1 = lv_label_create(ui_uiShelfLocationSelectorContainer);
    lv_obj_set_width(ui_uiShelfPositionItem1, lv_pct(20));
    lv_obj_set_height(ui_uiShelfPositionItem1, lv_pct(100));
    lv_obj_set_x(ui_uiShelfPositionItem1, -87);
    lv_obj_set_y(ui_uiShelfPositionItem1, -14);
    lv_obj_set_align(ui_uiShelfPositionItem1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_uiShelfPositionItem1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_uiShelfPositionItem1, "2");
    lv_obj_clear_flag(ui_uiShelfPositionItem1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_src(ui_uiShelfPositionItem1, &ui_img_hexagon_72dp_00e4f6_fill0_wght400_grad0_opsz48_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_uiShelfPositionItem1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_uiShelfPositionItem1, lv_color_hex(0xB962EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_uiShelfPositionItem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uiShelfPositionItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiShelfPositionItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiShelfPositionItem1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiShelfPositionItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem1, LV_PART_MAIN | LV_STATE_FOCUSED, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_text_align(ui_uiShelfPositionItem1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_FOCUSED);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem1, LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiShelfPositionItem1, LV_PART_MAIN | LV_STATE_FOCUSED,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_pad_left(ui_uiShelfPositionItem1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(ui_uiShelfPositionItem1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(ui_uiShelfPositionItem1, 12, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(ui_uiShelfPositionItem1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_uiShelfLedMappingContainer = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_uiShelfLedMappingContainer);
    lv_obj_set_width(ui_uiShelfLedMappingContainer, lv_pct(100));
    lv_obj_set_height(ui_uiShelfLedMappingContainer, lv_pct(30));
    lv_obj_set_align(ui_uiShelfLedMappingContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiShelfLedMappingContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiShelfLedMappingContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiShelfLedMappingContainer,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_uiShelfLedMappingContainer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfLedMappingContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiShelfLedMappingContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_width(ui_uiShelfLedMappingContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_uiShelfLedMappingContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uiShelfLedMappingContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer);
    lv_obj_set_height(ui_uiLedItemContainer, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem = lv_obj_create(ui_uiLedItemContainer);
    lv_obj_set_width(ui_uiLedItem, 16);
    lv_obj_set_height(ui_uiLedItem, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiLedItem, lv_color_hex(0x17569A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiLedItem, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiLedItem, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel = lv_label_create(ui_uiLedItemContainer);
    lv_obj_set_width(ui_uiLedItemLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel, "10");
    lv_obj_set_style_text_color(ui_uiLedItemLabel, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer1 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer1);
    lv_obj_set_width(ui_uiLedItemContainer1, 30);
    lv_obj_set_height(ui_uiLedItemContainer1, lv_pct(110));
    lv_obj_set_align(ui_uiLedItemContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItemContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem1 = lv_obj_create(ui_uiLedItemContainer1);
    lv_obj_set_width(ui_uiLedItem1, 16);
    lv_obj_set_height(ui_uiLedItem1, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiLedItem1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_uiLedItem1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Pink____________);
    lv_obj_set_style_border_color(ui_uiLedItem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_uiLedItem1, lv_color_hex(0xFF7ED3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_uiLedItem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_uiLedItem1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_uiLedItem1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel1 = lv_label_create(ui_uiLedItemContainer1);
    lv_obj_set_width(ui_uiLedItemLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel1, "12");
    ui_object_set_themeable_style_property(ui_uiLedItemLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_uiLedItemLabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Pink____________);

    ui_uiLedItemContainer2 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer2);
    lv_obj_set_height(ui_uiLedItemContainer2, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem2 = lv_obj_create(ui_uiLedItemContainer2);
    lv_obj_set_width(ui_uiLedItem2, 16);
    lv_obj_set_height(ui_uiLedItem2, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiLedItem2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiLedItem2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_color(ui_uiLedItem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel2 = lv_label_create(ui_uiLedItemContainer2);
    lv_obj_set_width(ui_uiLedItemLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel2, "10");
    lv_obj_add_flag(ui_uiLedItemLabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_uiLedItemLabel2, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer4 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer4);
    lv_obj_set_height(ui_uiLedItemContainer4, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem4 = lv_obj_create(ui_uiLedItemContainer4);
    lv_obj_set_width(ui_uiLedItem4, 16);
    lv_obj_set_height(ui_uiLedItem4, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiLedItem4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiLedItem4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_color(ui_uiLedItem4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel4 = lv_label_create(ui_uiLedItemContainer4);
    lv_obj_set_width(ui_uiLedItemLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel4, "10");
    lv_obj_add_flag(ui_uiLedItemLabel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_uiLedItemLabel4, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer5 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer5);
    lv_obj_set_height(ui_uiLedItemContainer5, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem5 = lv_obj_create(ui_uiLedItemContainer5);
    lv_obj_set_width(ui_uiLedItem5, 16);
    lv_obj_set_height(ui_uiLedItem5, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiLedItem5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiLedItem5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_color(ui_uiLedItem5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel5 = lv_label_create(ui_uiLedItemContainer5);
    lv_obj_set_width(ui_uiLedItemLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel5, "10");
    lv_obj_add_flag(ui_uiLedItemLabel5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_uiLedItemLabel5, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer3 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer3);
    lv_obj_set_height(ui_uiLedItemContainer3, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem3 = lv_obj_create(ui_uiLedItemContainer3);
    lv_obj_set_width(ui_uiLedItem3, 16);
    lv_obj_set_height(ui_uiLedItem3, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiLedItem3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Cyan____________);
    ui_object_set_themeable_style_property(ui_uiLedItem3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Cyan____________);
    lv_obj_set_style_border_color(ui_uiLedItem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel3 = lv_label_create(ui_uiLedItemContainer3);
    lv_obj_set_width(ui_uiLedItemLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel3, "10");
    lv_obj_add_flag(ui_uiLedItemLabel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_uiLedItemLabel3, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer12 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer12);
    lv_obj_set_width(ui_uiLedItemContainer12, 30);
    lv_obj_set_height(ui_uiLedItemContainer12, lv_pct(110));
    lv_obj_set_align(ui_uiLedItemContainer12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItemContainer12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem12 = lv_obj_create(ui_uiLedItemContainer12);
    lv_obj_set_width(ui_uiLedItem12, 16);
    lv_obj_set_height(ui_uiLedItem12, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiLedItem12, lv_color_hex(0xF6972E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiLedItem12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiLedItem12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_uiLedItem12, lv_color_hex(0xFAAA51), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_uiLedItem12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_uiLedItem12, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_uiLedItem12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel12 = lv_label_create(ui_uiLedItemContainer12);
    lv_obj_set_width(ui_uiLedItemLabel12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel12, "10");
    lv_obj_set_style_text_color(ui_uiLedItemLabel12, lv_color_hex(0xF6972E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer8 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer8);
    lv_obj_set_height(ui_uiLedItemContainer8, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem8 = lv_obj_create(ui_uiLedItemContainer8);
    lv_obj_set_width(ui_uiLedItem8, 16);
    lv_obj_set_height(ui_uiLedItem8, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiLedItem8, lv_color_hex(0x17569A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiLedItem8, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiLedItem8, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel8 = lv_label_create(ui_uiLedItemContainer8);
    lv_obj_set_width(ui_uiLedItemLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel8, "10");
    lv_obj_add_flag(ui_uiLedItemLabel8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_uiLedItemLabel8, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer9 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer9);
    lv_obj_set_height(ui_uiLedItemContainer9, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem9 = lv_obj_create(ui_uiLedItemContainer9);
    lv_obj_set_width(ui_uiLedItem9, 16);
    lv_obj_set_height(ui_uiLedItem9, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiLedItem9, lv_color_hex(0x17569A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiLedItem9, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiLedItem9, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel9 = lv_label_create(ui_uiLedItemContainer9);
    lv_obj_set_width(ui_uiLedItemLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel9, "15");
    lv_obj_set_style_text_color(ui_uiLedItemLabel9, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer10 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer10);
    lv_obj_set_height(ui_uiLedItemContainer10, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem10 = lv_obj_create(ui_uiLedItemContainer10);
    lv_obj_set_width(ui_uiLedItem10, 16);
    lv_obj_set_height(ui_uiLedItem10, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiLedItem10, lv_color_hex(0x17569A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiLedItem10, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiLedItem10, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel10 = lv_label_create(ui_uiLedItemContainer10);
    lv_obj_set_width(ui_uiLedItemLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel10, "10");
    lv_obj_add_flag(ui_uiLedItemLabel10, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_uiLedItemLabel10, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemContainer11 = lv_obj_create(ui_uiShelfLedMappingContainer);
    lv_obj_remove_style_all(ui_uiLedItemContainer11);
    lv_obj_set_height(ui_uiLedItemContainer11, lv_pct(100));
    lv_obj_set_width(ui_uiLedItemContainer11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_uiLedItemContainer11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiLedItemContainer11, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiLedItemContainer11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiLedItemContainer11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_uiLedItemContainer11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uiLedItemContainer11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uiLedItemContainer11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uiLedItemContainer11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItem11 = lv_obj_create(ui_uiLedItemContainer11);
    lv_obj_set_width(ui_uiLedItem11, 16);
    lv_obj_set_height(ui_uiLedItem11, lv_pct(80));
    lv_obj_set_align(ui_uiLedItem11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiLedItem11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiLedItem11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiLedItem11, lv_color_hex(0x17569A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiLedItem11, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiLedItem11, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiLedItem11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiLedItem11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLedItemLabel11 = lv_label_create(ui_uiLedItemContainer11);
    lv_obj_set_width(ui_uiLedItemLabel11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLedItemLabel11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLedItemLabel11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLedItemLabel11, "10");
    lv_obj_add_flag(ui_uiLedItemLabel11, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_uiLedItemLabel11, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLedItemLabel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiShelfActionsContainer = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_uiShelfActionsContainer);
    lv_obj_set_width(ui_uiShelfActionsContainer, lv_pct(100));
    lv_obj_set_height(ui_uiShelfActionsContainer, lv_pct(20));
    lv_obj_set_align(ui_uiShelfActionsContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiShelfActionsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_uiShelfActionsContainer, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_uiShelfActionsContainer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_uiShelfActionsContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiShelfLedMappingContainerOverly = lv_obj_create(ui_SHELF_1);
    lv_obj_set_height(ui_uiShelfLedMappingContainerOverly, 117);
    lv_obj_set_width(ui_uiShelfLedMappingContainerOverly, lv_pct(100));
    lv_obj_set_align(ui_uiShelfLedMappingContainerOverly, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_uiShelfLedMappingContainerOverly, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiShelfLedMappingContainerOverly, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiShelfLedMappingContainerOverly, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiShelfLedMappingContainerOverly, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiShelfLedMappingContainerOverly, lv_color_hex(0x101629), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiShelfLedMappingContainerOverly, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiShelfLedMappingContainerOverly, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiShelfLedMappingContainerOverly, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiShelfLedMappingContainerOverly, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_uiShelfLedMappingContainerOverly);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label9, "SELECT START");
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_text_letter_space(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_uiShelfLedMappingContainerOverly);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_height(ui_Container6, 60);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_align(ui_Container6, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_Container6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container6, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startLabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_startLabel, 72);
    lv_obj_set_height(ui_startLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startLabel, "12");
    ui_object_set_themeable_style_property(ui_startLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_startLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Pink____________);
    lv_obj_set_style_text_letter_space(ui_startLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_startLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 219);
    lv_obj_set_height(ui_Container8, 86);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_inputUpDowmLocation3 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_inputUpDowmLocation3);
    lv_obj_set_width(ui_inputUpDowmLocation3, lv_pct(75));
    lv_obj_set_height(ui_inputUpDowmLocation3, lv_pct(47));
    lv_obj_set_align(ui_inputUpDowmLocation3, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_inputUpDowmLocation3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_inputUpDowmLocation3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_inputUpDowmLocation3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_inputUpDowmLocation3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_inputUpDowmLocation3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_inputUpDowmLocation3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_inputUpDowmLocation3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inputUpDowmLocation3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_inputUpDowmLocation3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_inputUpDowmLocation3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiInputBtnUp3 = lv_label_create(ui_inputUpDowmLocation3);
    lv_obj_set_width(ui_uiInputBtnUp3, lv_pct(25));
    lv_obj_set_height(ui_uiInputBtnUp3, lv_pct(100));
    lv_obj_set_align(ui_uiInputBtnUp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputBtnUp3, "");
    lv_obj_set_style_bg_img_src(ui_uiInputBtnUp3, &ui_img_add_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnUp3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiInputBtnUp3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiInputBtnUp3, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiInputUpDownTotalLedsValue = lv_label_create(ui_inputUpDowmLocation3);
    lv_obj_set_width(ui_uiInputUpDownTotalLedsValue, lv_pct(50));
    lv_obj_set_height(ui_uiInputUpDownTotalLedsValue, lv_pct(100));
    lv_obj_set_align(ui_uiInputUpDownTotalLedsValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputUpDownTotalLedsValue, "6");

    ui_uiInputBtnDown3 = lv_label_create(ui_inputUpDowmLocation3);
    lv_obj_set_width(ui_uiInputBtnDown3, lv_pct(25));
    lv_obj_set_height(ui_uiInputBtnDown3, lv_pct(100));
    lv_obj_set_align(ui_uiInputBtnDown3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiInputBtnDown3, "");
    lv_obj_set_style_bg_img_src(ui_uiInputBtnDown3, &ui_img_remove_32dp_ffffff_fill0_wght400_grad0_opsz40_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Purple__________);
    ui_object_set_themeable_style_property(ui_uiInputBtnDown3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Purple__________);
    lv_obj_set_style_border_width(ui_uiInputBtnDown3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiInputBtnDown3, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Container8);
    lv_img_set_src(ui_Image10, &ui_img_arrow_drop_down_72dp_00e4f6_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Image10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_Pink____________);
    ui_object_set_themeable_style_property(ui_Image10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_Pink____________);
    lv_obj_set_style_pad_left(ui_Image10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Image10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Image10, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Image10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startLabel1 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_startLabel1, 72);
    lv_obj_set_height(ui_startLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startLabel1, "17");
    lv_obj_set_style_text_color(ui_startLabel1, lv_color_hex(0xF6972E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_startLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_startLabel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_startLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SHELF_2 = lv_tabview_add_tab(ui_TabView1, "2");

    ui_SHELF_3 = lv_tabview_add_tab(ui_TabView1, "3");

    ui_SHELF_4 = lv_tabview_add_tab(ui_TabView1, "4");

    ui_SHELF_5 = lv_tabview_add_tab(ui_TabView1, "5");

    ui_ADD_SHELF = lv_tabview_add_tab(ui_TabView1, "+");

}

void ui_SHELVES_SCREEN_screen_destroy(void)
{
    if(ui_SHELVES_SCREEN) lv_obj_del(ui_SHELVES_SCREEN);

    // NULL screen variables
    ui_SHELVES_SCREEN = NULL;
    ui_header2 = NULL;
    ui_BodyContainerShelvesScreen = NULL;
    ui_TabView1 = NULL;
    ui_SHELF_1 = NULL;
    ui_Container5 = NULL;
    ui_uiShelfInputsContainer = NULL;
    ui_uiShelfLocationsInputContainer = NULL;
    ui_Image1 = NULL;
    ui_inputUpDowmLocation = NULL;
    ui_uiInputBtnUp = NULL;
    ui_uiInputUpDownValue = NULL;
    ui_uiInputBtnDown = NULL;
    ui_uiShelfLedsInputContainer = NULL;
    ui_Image6 = NULL;
    ui_inputUpDowmLocation1 = NULL;
    ui_uiInputBtnUp1 = NULL;
    ui_uiInputUpDownValue1 = NULL;
    ui_uiInputBtnDown1 = NULL;
    ui_uiShelfLocationSelectorContainer = NULL;
    ui_uiShelfPositionItem = NULL;
    ui_uiShelfPositionItem1 = NULL;
    ui_uiShelfLedMappingContainer = NULL;
    ui_uiLedItemContainer = NULL;
    ui_uiLedItem = NULL;
    ui_uiLedItemLabel = NULL;
    ui_uiLedItemContainer1 = NULL;
    ui_uiLedItem1 = NULL;
    ui_uiLedItemLabel1 = NULL;
    ui_uiLedItemContainer2 = NULL;
    ui_uiLedItem2 = NULL;
    ui_uiLedItemLabel2 = NULL;
    ui_uiLedItemContainer4 = NULL;
    ui_uiLedItem4 = NULL;
    ui_uiLedItemLabel4 = NULL;
    ui_uiLedItemContainer5 = NULL;
    ui_uiLedItem5 = NULL;
    ui_uiLedItemLabel5 = NULL;
    ui_uiLedItemContainer3 = NULL;
    ui_uiLedItem3 = NULL;
    ui_uiLedItemLabel3 = NULL;
    ui_uiLedItemContainer12 = NULL;
    ui_uiLedItem12 = NULL;
    ui_uiLedItemLabel12 = NULL;
    ui_uiLedItemContainer8 = NULL;
    ui_uiLedItem8 = NULL;
    ui_uiLedItemLabel8 = NULL;
    ui_uiLedItemContainer9 = NULL;
    ui_uiLedItem9 = NULL;
    ui_uiLedItemLabel9 = NULL;
    ui_uiLedItemContainer10 = NULL;
    ui_uiLedItem10 = NULL;
    ui_uiLedItemLabel10 = NULL;
    ui_uiLedItemContainer11 = NULL;
    ui_uiLedItem11 = NULL;
    ui_uiLedItemLabel11 = NULL;
    ui_uiShelfActionsContainer = NULL;
    ui_uiShelfLedMappingContainerOverly = NULL;
    ui_Label9 = NULL;
    ui_Container6 = NULL;
    ui_startLabel = NULL;
    ui_Container8 = NULL;
    ui_inputUpDowmLocation3 = NULL;
    ui_uiInputBtnUp3 = NULL;
    ui_uiInputUpDownTotalLedsValue = NULL;
    ui_uiInputBtnDown3 = NULL;
    ui_Image10 = NULL;
    ui_startLabel1 = NULL;
    ui_SHELF_2 = NULL;
    ui_SHELF_3 = NULL;
    ui_SHELF_4 = NULL;
    ui_SHELF_5 = NULL;
    ui_ADD_SHELF = NULL;

}
