// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: minis_cabinet

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SETTINGS
extern void ui_SETTINGS_screen_init(void);
extern void ui_SETTINGS_screen_destroy(void);
extern lv_obj_t * ui_SETTINGS;
extern lv_obj_t * ui_header3;
extern lv_obj_t * ui_BodyContainer1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

